realtime cleverage: considerations of theoric time
hove-io/navitia pull request #1763
Opened 2016-09-13 10:03 UTC by patochectp

2016-09-13 10:15 UTC, TeXitoi commented
OK for me.

2016-09-13 13:30 UTC, antoine-de commented
I think it would be nice to add integration tests on this (to check weither the `is_real_time` is really used :wink: )

2016-09-15 09:06 UTC, patochectp commented
done

2016-09-15 09:24 UTC, antoine-de commented on source/jormungandr/tests/proxy_realtime_cleverage_integration_tests.py
> +        """
can you add some general comments on the test ? (even if the name is quite clear ?)

else you can remove the empty `""" """` :smile:

2016-09-15 09:24 UTC, antoine-de commented on source/jormungandr/tests/proxy_realtime_cleverage_integration_tests.py
> +        """
same here

2016-09-15 09:25 UTC, antoine-de requested changes
thanks for the integration tests!

2016-09-15 09:46 UTC, patochectp commented
done

2016-09-15 10:20 UTC, antoine-de approved these changes

2016-09-15 10:20 UTC, merged