Experimental: add integration test
hove-io/navitia pull request #1773
Opened 2016-09-19 14:12 UTC by xlqian

2016-09-21 13:52 UTC, TeXitoi commented
Jenkins, test this please.

2016-09-21 13:54 UTC, TeXitoi commented on source/jormungandr/tests/routing_tests_experimental.py
> +        assert j['sections'][0]['to']['id'] == 'stop_point:stopB'
You should check that the type is walking.

2016-09-21 13:54 UTC, TeXitoi requested changes

2016-10-04 13:14 UTC, kinnou02 commented
This PR has been waiting for two weeks!

2016-10-05 07:51 UTC, xlqian commented
@kinnou02 thx for reminding ...

2016-10-05 08:00 UTC, TeXitoi approved these changes

2016-10-05 10:53 UTC, merged