tyr: Add shape on user
hove-io/navitia pull request #1780
Opened 2016-09-22 12:33 UTC by patochectp

2016-09-22 14:04 UTC, kinnou02 commented on source/tyr/migrations/versions/44dab62dfff7_add_shape_on_user.py
> +"""empty message
You should explain what this migration do, this text will be shown at the execution of the migration

2016-09-22 14:08 UTC, kinnou02 commented on source/tyr/tyr/resources.py
> +        return ast.literal_eval(value)
What do you want to do here?
a simple `json.loads()` isn't enough?

2016-09-22 14:10 UTC, kinnou02 commented on source/tyr/tyr/resources.py
> +            features =  ast.literal_eval(args['shape'])
Same thing here, a `json.loads` should be enough.
Json look like python dict, but evaluating it as a python object is wrong

2016-09-22 14:15 UTC, kinnou02 requested changes
Did you run the tyr test manually? they aren't run by ctest or jenkins currently :(

2016-09-22 14:18 UTC, datanel commented on source/tyr/tyr/resources.py
> +            validation = is_valid(FeatureCollection(features))
is this always FeatureCollection or Feature is valid too?

2016-09-23 11:50 UTC, datanel commented on source/tyr/tyr/validations.py
> +        features= value.get('features')
what happen if I post a Feature (not a FeatureCollection) ?
```
{
  "type": "Feature",
  "geometry": {
    "type": "Point",
    "coordinates": [125.6, 10.1]
  },
  "properties": {
    "name": "Dinagat Islands"
  }
}
```
This geojosn has no attribute "features"
[http://geojson.org/](http://geojson.org/)

2016-09-23 11:53 UTC, datanel commented
When I test with postman or curl
I have the following errors

```
Traceback (most recent call last):
  File "/home/dquintanel/.virtualenv/tyr/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/dquintanel/.virtualenv/tyr/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/dquintanel/.virtualenv/tyr/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/home/dquintanel/.virtualenv/tyr/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dquintanel/.virtualenv/tyr/lib/python2.7/site-packages/flask_restful/__init__.py", line 268, in error_router
    return self.handle_error(e)
  File "/home/dquintanel/.virtualenv/tyr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dquintanel/.virtualenv/tyr/lib/python2.7/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/home/dquintanel/.virtualenv/tyr/lib/python2.7/site-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
```

2016-09-23 15:13 UTC, merged