List users with shape
hove-io/navitia pull request #1789
Opened 2016-09-26 15:59 UTC by patochectp

2016-09-28 18:11 UTC, pbougue requested changes
Looks good to me except for the default value

2016-09-28 18:11 UTC, pbougue commented on source/tyr/tyr/resources.py
> +                            default=False,
default is True (will change tests) : we don't want to output shape by default

2016-09-28 18:11 UTC, pbougue commented on source/tyr/tests/integration/users_test.py
> +    resp = api_get('/v0/users/{}'.format(create_user))
will need explicit `disable_geojson=False`

2016-09-28 18:11 UTC, pbougue commented on source/tyr/tests/integration/users_test.py
> +def test_get_user_with_shape_and_disable_geojson_param_true(create_user, geojson_feature_collection):
would be nice to test the same but not providing param, see that we default to `disable_geojson=True`

2016-09-29 07:36 UTC, datanel commented on source/tyr/tyr/resources.py
> +                            default=False,
> we don't want to output shape by default

why?

copied from **https://github.com/CanalTP/navitia/blob/dev/source/jormungandr/jormungandr/interfaces/v1/Disruptions.py#L91**

2016-09-29 08:01 UTC, merged

2016-09-29 08:03 UTC, datanel commented on source/tyr/tyr/resources.py
> +                            default=False,
I merge and will make another PR if we change this behaviour