Jormungandr: expose bss realtime availability in /journeys
hove-io/navitia pull request #1819
Opened 2016-10-06 11:29 UTC by rchoquet

### Exposes the realtime bss availability in /journeys for departure & arrival places.

Not sure if it lacks some tests or if I put some pieces of code in the wrong place \o/, let me now !

2016-10-07 08:56 UTC, xlqian commented on source/jormungandr/jormungandr/interfaces/v1/Journeys.py
> +        if parser_get.parse_args()["bss_stands"]:
prefer using `if parser_get.parse_args().get("bss_stands")`

2016-10-07 08:56 UTC, xlqian commented on source/jormungandr/jormungandr/parking_space_availability/bss/bss_provider_manager.py
> +        for place in (s[from_to] for j in journeys for s in j['sections'] for from_to in ('from', 'to') if from_to in s):
`for place in (s.get(from_to, {}) for j in journeys for s in j.get('sections', []) for from_to in ('from', 'to'))`

2016-10-07 08:56 UTC, xlqian commented on source/jormungandr/tests/bss_provider_tests.py
> +                    assert 'stands' not in place['poi']
L387 and L388 can be replaced by ` assert 'stands' not in place.get('poi', {})`

2016-10-07 08:56 UTC, xlqian commented on source/jormungandr/tests/bss_provider_tests.py
> +        return (s[from_to] for j in journeys for s in j['sections'] for from_to in ('from', 'to') if from_to in s)
`for place in (s.get(from_to, {}) for j in journeys for s in j.get('sections', []) for from_to in ('from', 'to'))`

2016-10-07 09:23 UTC, TeXitoi requested changes

2016-10-07 09:23 UTC, TeXitoi commented on source/jormungandr/tests/bss_provider_tests.py
> +        return (s[from_to] for j in journeys for s in j['sections'] for from_to in ('from', 'to') if from_to in s)
You can mutualize that with bss_provider_manager.py. A free function in bss_provider_manager.py will do the job. You can even include the filter on poi.

2016-10-07 13:43 UTC, rchoquet commented
Jenkins, test this please.

2016-10-10 08:06 UTC, TeXitoi approved these changes

2016-10-10 08:30 UTC, xlqian approved these changes

2016-10-10 08:30 UTC, merged