Jormungandr: update some integration tests
hove-io/navitia pull request #1822
Opened 2016-10-12 10:04 UTC by xlqian

2016-10-12 21:15 UTC, TeXitoi requested changes

2016-10-12 21:15 UTC, TeXitoi commented on source/jormungandr/tests/routing_tests_experimental.py
> +        pass
Looking at the title of the test, you should just use another way to get the direct path that don't use type filter. Using max_duration=0 should do the trick

2016-10-12 21:15 UTC, TeXitoi commented on source/jormungandr/tests/routing_tests_new_default.py
> +        pass
same as in experimental.

2016-10-13 08:14 UTC, xlqian commented on source/jormungandr/tests/routing_tests_experimental.py
> +        pass
you're right, this test shouldn't be overwritten...

2016-10-13 08:14 UTC, xlqian commented on source/jormungandr/tests/routing_tests_new_default.py
> +        pass
ok

2016-10-19 10:34 UTC, TeXitoi approved these changes

2016-10-19 10:40 UTC, TeXitoi commented
It should fix a lot of artemis tests.

2016-10-21 08:58 UTC, merged