Jormungandr: fix test_sp_to_sp for experimental
hove-io/navitia pull request #1826
Opened 2016-10-13 14:29 UTC by xlqian

2016-10-13 15:42 UTC, TeXitoi requested changes

2016-10-13 15:42 UTC, TeXitoi commented on source/jormungandr/tests/journey_common_tests.py
> +
I'd prefer to check that the first (resp last) section is a public_transport section with from (resp to) = request from (resp to).

2016-10-14 08:58 UTC, TeXitoi commented on source/jormungandr/tests/journey_common_tests.py
> +
Sorry, that's not the problem. But we shouldn't have this journey if we want to be isofunctional. Maybe that should be done in another ticket.

2016-10-14 08:59 UTC, TeXitoi approved these changes

2016-10-17 10:41 UTC, xlqian commented on source/jormungandr/tests/journey_common_tests.py
> +
i created a ticket for that

2016-10-19 10:36 UTC, TeXitoi commented
Will be fixed globally in another PR

2016-10-19 10:36 UTC, closed without merging