jormungandr: parameters in request used for direct_path
hove-io/navitia pull request #1832
Opened 2016-10-24 08:51 UTC by kadhikari

Since parameters of an instance always have default values,
we should use parameter values of the request.

2016-10-25 12:27 UTC, TeXitoi requested changes

2016-10-25 12:27 UTC, TeXitoi commented on source/jormungandr/tests/routing_tests_experimental.py
> +        assert('journeys' not in response)
All these tests should be in JourneyCommon

2016-10-26 12:39 UTC, kadhikari commented
@TeXitoi i made some corrections

2016-10-26 16:50 UTC, TeXitoi approved these changes

2016-10-26 16:50 UTC, merged