Clean skipped integration tests in scenarios
hove-io/navitia pull request #1836
Opened 2016-11-02 10:26 UTC by kadhikari

2016-11-02 16:11 UTC, TeXitoi requested changes

2016-11-02 16:11 UTC, TeXitoi commented on source/jormungandr/tests/routing_tests_experimental.py
> +        assert('journeys' not in response)
We should have a journey here. This overload is buggy.

2016-11-03 15:49 UTC, kadhikari commented
@TeXitoi, I modified the test

2016-11-04 09:29 UTC, TeXitoi approved these changes

2016-11-04 09:29 UTC, merged