Experimental Feature iti 224 tad in experimental
hove-io/navitia pull request #1841
Opened 2016-11-09 11:26 UTC by kadhikari

2016-11-09 11:51 UTC, TeXitoi requested changes

2016-11-09 11:51 UTC, TeXitoi commented on source/jormungandr/jormungandr/georef.py
> +        req.requested_api = type_pb2.odt_stop_points
Setting that one time is enough.

2016-11-09 11:51 UTC, TeXitoi commented on source/jormungandr/jormungandr/scenarios/experimental.py
> +embedded_type_coord = {"STOP_POINT": "stop_point", "STOP_AREA": "stop_area", "ADDRESS": "address"}
Useless

2016-11-09 11:51 UTC, TeXitoi commented on source/jormungandr/jormungandr/scenarios/experimental.py
> +        crow_fly_stop_points = dict()
Please add a comment explaining the value of this dict. That's not straightforward.

2016-11-09 11:51 UTC, TeXitoi commented on source/kraken/worker.cpp
> +    std::cout << "zonal_sps size: " << zonal_sps.size() << std::endl;
debug

2016-11-09 11:51 UTC, TeXitoi commented on source/kraken/worker.cpp
> +    return pb_creator.get_response();
```c++
return get_response(zonal_sps, *data, 0);
```

and you don't need all that.

2016-11-09 11:51 UTC, TeXitoi commented on source/type/pb_converter.cpp
> +
not needed.

2016-11-09 16:41 UTC, kadhikari commented
@TeXitoi i pushed some modifications

2016-11-09 17:59 UTC, TeXitoi commented on source/jormungandr/jormungandr/scenarios/experimental.py
> +        #a crow_fly section is added only if stop_point is not zonal
So `crow_fly_stop_points['toto']` correspond to 'toto is zonal odt? the variable name is quite illisible.

I don't have any good name to propose.

2016-11-09 17:59 UTC, TeXitoi approved these changes

2016-11-10 08:59 UTC, xlqian approved these changes

2016-11-10 08:59 UTC, xlqian commented on source/jormungandr/jormungandr/scenarios/experimental.py
> +        #a crow_fly section is added only if stop_point is not zonal
why not using a set instead of dict? and name it `zonal_odt_stop_points`?

2016-11-15 13:31 UTC, kadhikari commented on source/jormungandr/jormungandr/scenarios/experimental.py
> +        #a crow_fly section is added only if stop_point is not zonal
Since we use three properties on a stop_point : exist, non-odt and odt we can't use a set. You could propose me some variable names?

2016-11-15 15:47 UTC, kadhikari commented
@xlqian  i used two variables to manage crow_fly section and odt.

2016-11-15 16:06 UTC, xlqian approved these changes

2016-11-17 14:59 UTC, kadhikari commented
@TeXitoi, @xlqian i added an integration test for odt

2016-11-17 15:35 UTC, TeXitoi approved these changes

2016-11-17 17:18 UTC, merged