Async experimental
hove-io/navitia pull request #1844
Opened 2016-11-10 15:14 UTC by azime

Support async call kraken in experimental scenario

2016-11-15 10:11 UTC, kinnou02 requested changes

2016-11-15 10:11 UTC, kinnou02 commented on source/jormungandr/jormungandr/scenarios/experimental.py
> +import gevent, gevent.pool
I like import to be on the top of the file.

2016-11-15 10:11 UTC, kinnou02 commented on source/jormungandr/jormungandr/scenarios/experimental.py
> +    if not fall_back_origins or not fall_back_destinations or not request.get('max_duration', 0):
Almost everywhere we use fallback in one word not two.

2016-11-15 10:11 UTC, kinnou02 commented on source/jormungandr/jormungandr/scenarios/experimental.py
> +    def _get_direct_path(self, instance, mode, pt_object_origin, pt_object_destination, datetime, clockwise,
I am a little confuse about all of this, so this function act as a cache to not compute the same direct multiple time right?

2016-11-15 10:11 UTC, kinnou02 commented on source/jormungandr/jormungandr/scenarios/experimental.py
> +            futures = worker._get_crowfly_futures(g.requested_origin,
This seems to be mostly based on side effect, I don't like side effect and async, it's complex and error prone

2016-11-15 10:11 UTC, kinnou02 commented on source/jormungandr/jormungandr/scenarios/experimental.py
> +            futures = worker._get_routing_matrix_fustures(g.requested_origin, g.requested_destination,
There is a lot of abstraction level and absolute not explanation about what happen, why at that moment.
I have count at least seven steps, why do we do one before the other?

2016-11-16 11:03 UTC, xlqian commented on source/jormungandr/jormungandr/scenarios/experimental.py
> +                crow_fly_stop_points = set(list(crow_fly_stop_points) + resp[0])
`crow_fly_stop_points.add(resp[0])` ?

2016-11-21 08:57 UTC, xlqian commented
Jenkins, test this please!

2016-11-21 14:33 UTC, kinnou02 requested changes

2016-11-21 14:33 UTC, kinnou02 commented on source/jormungandr/jormungandr/scenarios/experimental.py
> +gevent.monkey.patch_socket()
We should do the monkey patching in the init of jormun, else importing the scenario would have induce a side effect

2016-11-21 14:33 UTC, kinnou02 commented on source/jormungandr/jormungandr/scenarios/experimental.py
> +            for future in gevent.iwait(orig_futures):
You don't have to do a `joinall` if you use `iwait`

2016-11-21 14:33 UTC, kinnou02 commented on source/jormungandr/jormungandr/scenarios/experimental.py
> +            if (dep_mode, origin.uri) not in called_modes:
We don't need the `origin.uri` here no?

2016-11-21 14:33 UTC, kinnou02 commented on source/jormungandr/jormungandr/scenarios/experimental.py
> +            orig_futures, dest_futures = worker.get_crowfly_futures(g.requested_origin, g.requested_destination)
comment to add:
First we search all stop_point reachable for each modes from the origin and the destination

2016-11-21 14:33 UTC, kinnou02 commented on source/jormungandr/jormungandr/scenarios/experimental.py
> +            orig_futures, dest_futures = worker.get_routing_matrix_futures(g.requested_origin,
Comment to add:
Then we want to put a arrival time for each of this stop points.
As a side note this won't work the day when our ETA will be impacted by the datetime of the journey, at least for the arrival when doing a "departure after" request.

2016-11-21 14:33 UTC, kinnou02 commented on source/jormungandr/jormungandr/scenarios/experimental.py
> +            orig_futures, dest_futures = worker.get_update_crowfly_duration_futures()
If I understand correctly we update the stop_points of the requested stop_area to set the ETA at 0, if so this call to kraken can have be made earlier.

2016-11-21 14:33 UTC, kinnou02 commented on source/jormungandr/jormungandr/scenarios/experimental.py
> +        futures = worker.get_direct_path_futures(self._get_direct_path,
Comment to add:
we compute the direct path for this journey, their time will be used to initialized our PT calls

2016-11-21 14:33 UTC, kinnou02 commented on source/jormungandr/jormungandr/scenarios/experimental.py
> +        futures = worker.get_journey_futures(g.requested_origin, g.requested_destination,
Comment to add:
We launch the PT journey planning

This calls could be launched earlier, as soon as we have the direct_path duration for the requested mode

2016-11-21 14:33 UTC, kinnou02 commented on source/jormungandr/jormungandr/scenarios/experimental.py
> +            direct_path = g.fallback_direct_path.get(dp_key)
I didn't see where we compute the fallback direct_path

2016-11-21 14:33 UTC, kinnou02 commented on source/jormungandr/jormungandr/scenarios/experimental.py
> +        futures = worker.build_journeys(self._extend_journey, map_response, crow_fly_stop_points)
Comment to add:
We compute the fallback part of our PT journeys

2016-11-21 14:33 UTC, kinnou02 commented on source/jormungandr/jormungandr/scenarios/experimental.py
> +        for future in gevent.iwait(futures):
Why not do that direclty in `build_journey`?

2016-11-21 15:08 UTC, xlqian commented on source/jormungandr/jormungandr/scenarios/experimental.py
> +gevent.monkey.patch_socket()
done

2016-11-21 15:08 UTC, xlqian commented on source/jormungandr/jormungandr/scenarios/experimental.py
> +            if (dep_mode, origin.uri) not in called_modes:
I have simplified that logic :)

2016-11-21 15:08 UTC, xlqian commented on source/jormungandr/jormungandr/scenarios/experimental.py
> +            orig_futures, dest_futures = worker.get_routing_matrix_futures(g.requested_origin,
Yep, I'm adding a lot of comments :)

2016-11-21 15:08 UTC, xlqian commented on source/jormungandr/jormungandr/scenarios/experimental.py
> +            for future in gevent.iwait(orig_futures):
I imagined a scenario as followed: 

We need to compute some crowfly stop_points with "walking" and "bike" respectively for "from" and "to", in this case we'll get 4 requests for stop_points.

**WITH** `joinall`: all requests are launched at the same time thanks to the concatenation
**WITHOUT** `joinall`: only 2 requests are parallelized 

That's why i did with `joinall`

2016-11-21 17:04 UTC, xlqian commented on source/jormungandr/jormungandr/scenarios/experimental.py
> +            orig_futures, dest_futures = worker.get_update_crowfly_duration_futures()
Hmm, this functions update the sn_routing_matrix if the stop_points is contained by stop_area, so we can only do this after the computation of sn_routing_matrix

2016-11-21 17:04 UTC, xlqian commented on source/jormungandr/jormungandr/scenarios/experimental.py
> +        futures = worker.get_journey_futures(g.requested_origin, g.requested_destination,
`This calls could be launched earlier, as so......`
Nope, we need the `global` direct_path duration to launch this pt computation

2016-11-21 17:04 UTC, xlqian commented on source/jormungandr/jormungandr/scenarios/experimental.py
> +            direct_path = g.fallback_direct_path.get(dp_key)
my bad, i'm improving this

2016-11-21 17:09 UTC, xlqian commented on source/jormungandr/jormungandr/scenarios/experimental.py
> +    def _get_direct_path(self, instance, mode, pt_object_origin, pt_object_destination, datetime, clockwise,
I'm improving this (which is not that easy)

2016-11-22 09:28 UTC, xlqian commented on source/jormungandr/jormungandr/scenarios/experimental.py
> +            for future in gevent.iwait(orig_futures):
I removed the iwait :)

2016-11-22 15:38 UTC, azime commented on source/jormungandr/jormungandr/scenarios/experimental.py
> +            self.nb_kraken_calls += 1
to delete ?

2016-11-24 14:33 UTC, xlqian commented
I benched on `new_default` w/wo `gevet.monkey.patch_socket()` There is no regression in performance.

2016-11-25 09:13 UTC, kinnou02 approved these changes

2016-11-25 14:21 UTC, merged