Fix partial terminus
hove-io/navitia pull request #1878
Opened 2016-12-01 09:18 UTC by azime

2016-12-02 09:31 UTC, TeXitoi commented on source/time_tables/departure_boards.cpp
> +            && (stop_time->vehicle_journey->stop_time_list.back().stop_point == stp);
minor: useless parenthesis

2016-12-02 09:31 UTC, TeXitoi commented on source/time_tables/departure_boards.cpp
>              }
A function for this loop will increase readability.

2016-12-02 10:23 UTC, pbougue commented on source/time_tables/departure_boards.cpp
> +                auto& jp_idx = pb_creator.data.dataRaptor->jp_container.get_jp_from_vj()[navitia::routing::VjIdx(*st.second->vehicle_journey)];
line length

2016-12-02 10:24 UTC, azime commented on source/time_tables/departure_boards.cpp
> +            && (stop_time->vehicle_journey->stop_time_list.back().stop_point == stp);
ok

2016-12-02 10:28 UTC, azime commented on source/time_tables/departure_boards.cpp
>              }
OK

2016-12-02 10:40 UTC, azime commented on source/time_tables/departure_boards.cpp
> +                auto& jp_idx = pb_creator.data.dataRaptor->jp_container.get_jp_from_vj()[navitia::routing::VjIdx(*st.second->vehicle_journey)];
ok

2016-12-02 11:08 UTC, xlqian commented on source/time_tables/departure_boards.cpp
> +            && stop_time->vehicle_journey->stop_time_list.back().stop_point
this line maybe redundant with L53?

2016-12-03 13:32 UTC, TeXitoi commented on source/time_tables/departure_boards.cpp
> +        }
```c++
if (last_jpp.sp_idx != sp_route.first) { return false; }
```

2016-12-03 13:32 UTC, TeXitoi commented on source/time_tables/departure_boards.cpp
> +    return last_stoptime;
```c++
return true;
```

2016-12-05 08:55 UTC, azime commented on source/time_tables/departure_boards.cpp
> +        }
ok

2016-12-05 08:55 UTC, azime commented on source/time_tables/departure_boards.cpp
> +    return last_stoptime;
ok

2016-12-05 15:43 UTC, TeXitoi approved these changes

2016-12-06 11:51 UTC, pbougue requested changes

2016-12-06 11:51 UTC, pbougue commented on source/jormungandr/tests/departure_board_tests.py
> +        # Stop_schedules in TStop2: Only VJ2 in response
Minor: A little ascii art showing stop times depending on dates here (for all in once to understand below and above also) would be nice.

2016-12-06 11:51 UTC, pbougue commented on source/time_tables/tests/departure_board_test_data.h
> +        b.vj("line:A", "1", "", true, "week")("stop1", 10 * 3600, 10 * 3600 + 10 * 60)
:+1: for new line, would be even clearer with `"10:10"_t, "10:10"_t`

2016-12-06 11:51 UTC, pbougue commented on source/jormungandr/tests/departure_board_tests.py
> +        assert len(response["stop_schedules"][0]["date_times"]) == 1
maybe add a check on time also (`"11;00"_t` if I guess correctly)

2016-12-06 11:51 UTC, pbougue commented on source/jormungandr/tests/departure_board_tests.py
> +        assert len(response["stop_schedules"][0]["date_times"]) == 1
And add a comment on the fact that we don't want to have 2 times (as one is terminus)

2016-12-06 11:51 UTC, pbougue commented on source/jormungandr/tests/departure_board_tests.py
> +        # Stop_schedules in TStop2: Partial Terminus
this "partial terminus" name is a little misleading to me, as for now it is more a test on the service days (just testing if it's served all week or not). So at least a comment is welcome.

2016-12-06 11:51 UTC, pbougue commented on source/time_tables/tests/departure_boards_test.cpp
> +        BOOST_REQUIRE_EQUAL(resp.stop_schedules(0).response_status(), pbnavitia::ResponseStatus::terminus);
maybe a check `BOOST_CHECK(stop_schedule.date_times_size() == 0);` (not tested)

2016-12-06 11:51 UTC, pbougue commented on source/time_tables/tests/departure_boards_test.cpp
> +    BOOST_REQUIRE_EQUAL(stop_schedule.date_times_size(), 0);
Not sure that this is the spirit of this test

2016-12-06 11:51 UTC, pbougue commented on source/time_tables/departure_boards.cpp
> +            && stop_time->vehicle_journey->route->destination
why do you need to check that you have a destination here? (maybe to "outsource")

2016-12-06 11:51 UTC, pbougue commented on source/time_tables/departure_boards.cpp
> +                                const stop_point_route& sp_route) {
shouldn't that be named `RoutePoint`?

2016-12-06 11:51 UTC, pbougue commented on source/time_tables/departure_boards.cpp
> +static bool is_partial_terminus(const PbCreator& pb_creator,
`is_flagged_partial_terminus` would be a better name, as it sometimes is a partial terminus, but you don't flag it that way as you don't have times. (or maybe outsource the `! stop_times.empty()` test)

2016-12-06 13:09 UTC, pbougue reviewed
Not sure it works when route's destination is in the middle of the vj: I'd check if the test on terminus is too simple.

2016-12-06 16:09 UTC, azime commented on source/time_tables/tests/departure_boards_test.cpp
> +        BOOST_REQUIRE_EQUAL(resp.stop_schedules(0).response_status(), pbnavitia::ResponseStatus::terminus);
OK

2016-12-06 16:26 UTC, azime commented on source/time_tables/tests/departure_board_test_data.h
> +        b.vj("line:A", "1", "", true, "week")("stop1", 10 * 3600, 10 * 3600 + 10 * 60)
ok

2016-12-06 16:29 UTC, azime commented on source/time_tables/departure_boards.cpp
> +static bool is_partial_terminus(const PbCreator& pb_creator,
OK

2016-12-06 16:30 UTC, azime commented on source/time_tables/departure_boards.cpp
> +            && stop_time->vehicle_journey->route->destination
OK

2016-12-06 16:59 UTC, azime commented on source/jormungandr/tests/departure_board_tests.py
> +        assert len(response["stop_schedules"][0]["date_times"]) == 1
OK

2016-12-07 15:24 UTC, pbougue commented on source/jormungandr/tests/departure_board_tests.py
> +        response = self.query_region("stop_areas/Tstop2/stop_schedules?"
Add same test on Tstop1 (we should have 1 date_time)

2016-12-07 15:24 UTC, pbougue commented on source/time_tables/tests/departure_boards_test.cpp
> +    BOOST_REQUIRE_EQUAL(stop_schedule.date_times_size(), 0);
Add a stop_point after maybe to avoid the terminus effect

2016-12-07 16:04 UTC, azime commented on source/jormungandr/tests/departure_board_tests.py
> +        response = self.query_region("stop_areas/Tstop2/stop_schedules?"
OK

2016-12-08 11:02 UTC, pbougue reviewed
Great!

2016-12-08 11:02 UTC, pbougue commented on source/jormungandr/tests/departure_board_tests.py
> +        assert len(response["stop_schedules"][0]["date_times"]) == 1
Done

2016-12-08 11:02 UTC, pbougue commented on source/jormungandr/tests/departure_board_tests.py
> +        response = self.query_region("stop_areas/Tstop2/stop_schedules?"
Done

2016-12-08 11:02 UTC, pbougue commented on source/time_tables/tests/departure_boards_test.cpp
> +    navitia::apply_disruption(b.impact(nt::RTLevel::Adapted, "Disruption stop2")
The best here (now that you added fork route) would be to disrupt on `StopR1`, and check below that on `StopR2` you have the 2 vj at `10:30`, when using calendar `not_associated_cal`.
To discuss if it's a pain.

2016-12-08 11:03 UTC, pbougue approved these changes

2016-12-08 17:49 UTC, pbougue commented on source/time_tables/tests/departure_boards_test.cpp
> +    navitia::apply_disruption(b.impact(nt::RTLevel::Adapted, "Disruption stop2")
Done

2016-12-08 18:28 UTC, merged