forward uri when not findable
hove-io/navitia pull request #1885
Opened 2016-12-05 16:32 UTC by xlqian

2016-12-05 18:10 UTC, pbougue reviewed
Not sure to understand a use case for that PR. Can it affect other endpoints?

2016-12-06 10:17 UTC, xlqian commented
@TeXitoi `new_default` and `experimental` return exactly the same response :tada:

2016-12-06 10:22 UTC, xlqian commented
@pbougue you can try this request: http://canaltp.github.io/navitia-playground/play.html?request=http%3A%2F%2Fnavitia2-ws.ctp.dev.canaltp.fr%2Fv1%2Fcoverage%2Ffr-auv%2Fjourneys%3Ffirst_section_mode%255B%255D%3Dcar%26from%3D2.9201546%253B45.8603889%26count%3D1%26to%3D3.0029581%253B45.8646066%26max_duration%3D0%26last_section_mode%255B%255D%3Dcar%26_override_scenario%3Dexperimental%26&token=f4b98e72-9769-400b-b541-05e2e2b30e8c    

in this request, `from` is a place which has no label/name/id, so this line https://github.com/CanalTP/navitia/pull/1885/files#diff-05cbd102661a0da9e75756727f9715bfL45 crashed like a comet....

2016-12-06 16:34 UTC, TeXitoi requested changes
Tests please.

2016-12-06 16:34 UTC, TeXitoi commented on source/jormungandr/jormungandr/georef.py
> +        if "coord:" in place:
`place.startswith("coord:")`?

2016-12-08 11:51 UTC, TeXitoi commented on source/jormungandr/tests/journey_common_tests.py
> +        When the departure is stop_area:A and the destination is stop_point:B belonging to stop_area:B
unsyncronised comment

2016-12-08 11:51 UTC, TeXitoi approved these changes

2016-12-09 09:42 UTC, merged