Feature iti 248 reuse protobuf response
hove-io/navitia pull request #1890
Opened 2016-12-08 13:47 UTC by kadhikari

concerned ticket: http://jira.canaltp.fr/browse/ITI-248

2016-12-09 10:57 UTC, xlqian reviewed
good job!

2016-12-09 10:57 UTC, xlqian commented on source/kraken/tests/direct_path_test.cpp
> +    //auto * data_ptr = data_manager.get_data().get();
comments are still useful?

2016-12-09 10:57 UTC, xlqian commented on source/ptreferential/ptreferential_api.cpp
> +    //pbnavitia::Response pb_response;
to remove?

2016-12-09 10:57 UTC, xlqian commented on source/routing/raptor_api.cpp
> +                              type::EntryPoint center,
can it be a const ref? or ref?

2016-12-09 10:57 UTC, xlqian commented on source/routing/raptor_api.cpp
> +                   type::EntryPoint center,
const ref? ref?

2016-12-09 10:57 UTC, xlqian commented on source/time_tables/route_schedules.cpp
> +        auto  matrice = make_matrice(stop_times, thermometer, *pb_creator.data);
make_matrix :)  i know it's not your codes

2016-12-09 14:47 UTC, TeXitoi requested changes
:+1:

2016-12-09 14:47 UTC, TeXitoi commented on source/kraken/kraken_zmq.h
> +        if(!pb_req.ParseFromArray(request.data(), request.size())){
training spaces

2016-12-09 14:47 UTC, TeXitoi commented on source/kraken/tests/direct_path_test.cpp
> +    //w.pb_creator.init(data_ptr, boost::gregorian::not_a_date_time, null_time_period);
comment cleanup needed.

2016-12-09 14:47 UTC, TeXitoi commented on source/kraken/tests/direct_path_test.cpp
> +    //w.pb_creator.init(data_ptr, boost::gregorian::not_a_date_time, null_time_period);
comment cleanup

2016-12-09 14:47 UTC, TeXitoi commented on source/kraken/worker.cpp
> +    //auto status = result.mutable_geo_status();
comment cleanup

2016-12-09 14:47 UTC, TeXitoi commented on source/kraken/worker.cpp
> +bool Worker::set_journeys_args(const pbnavitia::JourneysRequest& request,
A small comment explaining the return value.

2016-12-09 14:47 UTC, TeXitoi commented on source/ptreferential/ptreferential_api.cpp
> +    //pbnavitia::Response pb_response;
comment

2016-12-09 14:47 UTC, TeXitoi commented on source/time_tables/tests/departure_boards_test.cpp
> +    //navitia::PbCreator pb_creator1(data_ptr, "20150616T080000"_dt, null_time_period);
comment

2016-12-09 14:47 UTC, TeXitoi commented on source/type/pb_converter.cpp
> +    //return std::move(response);
comment

2016-12-09 16:30 UTC, kadhikari commented on source/kraken/tests/direct_path_test.cpp
> +    //auto * data_ptr = data_manager.get_data().get();
ok

2016-12-09 16:30 UTC, kadhikari commented on source/ptreferential/ptreferential_api.cpp
> +    //pbnavitia::Response pb_response;
ok

2016-12-09 16:32 UTC, kadhikari commented on source/time_tables/route_schedules.cpp
> +        auto  matrice = make_matrice(stop_times, thermometer, *pb_creator.data);
done

2016-12-09 16:33 UTC, kadhikari commented on source/kraken/kraken_zmq.h
> +        if(!pb_req.ParseFromArray(request.data(), request.size())){
ok

2016-12-09 16:33 UTC, kadhikari commented on source/kraken/tests/direct_path_test.cpp
> +    //w.pb_creator.init(data_ptr, boost::gregorian::not_a_date_time, null_time_period);
done

2016-12-09 16:33 UTC, kadhikari commented on source/kraken/tests/direct_path_test.cpp
> +    //w.pb_creator.init(data_ptr, boost::gregorian::not_a_date_time, null_time_period);
done

2016-12-09 16:34 UTC, kadhikari commented on source/kraken/worker.cpp
> +    //auto status = result.mutable_geo_status();
done

2016-12-09 16:34 UTC, kadhikari commented on source/ptreferential/ptreferential_api.cpp
> +    //pbnavitia::Response pb_response;
done

2016-12-09 16:37 UTC, kadhikari commented on source/time_tables/tests/departure_boards_test.cpp
> +    //navitia::PbCreator pb_creator1(data_ptr, "20150616T080000"_dt, null_time_period);
done

2016-12-09 16:38 UTC, kadhikari commented on source/type/pb_converter.cpp
> +    //return std::move(response);
done

2016-12-12 09:57 UTC, TeXitoi approved these changes

2016-12-12 11:16 UTC, merged

2016-12-12 11:31 UTC, pbougue commented on source/autocomplete/autocomplete_api.cpp
> +void autocomplete(navitia::PbCreator& pb_creator, const std::string &q,
indent

2016-12-12 11:31 UTC, pbougue commented on source/autocomplete/autocomplete_api.h
> +void autocomplete(navitia::PbCreator& pb_creator, const std::string &q,
indent

2016-12-12 11:31 UTC, pbougue commented on source/calendar/calendar_api.cpp
> +          const navitia::type::Data &d,
indent

2016-12-12 11:31 UTC, pbougue commented on source/calendar/calendar_api.cpp
> -                              const boost::posix_time::ptime& current_datetime,
are you sure it's not gonna prevent from debug (as you use `now` after), or imply some bugs to remove current_dt? (same question everywhere, so I guess you thinked about it)

2016-12-12 11:31 UTC, pbougue commented on source/calendar/calendar_api.h
> +          const navitia::type::Data &d,
indent

2016-12-12 11:31 UTC, pbougue commented on source/jormungandr/tests/ptref_tests.py
> +        feed_publisher = feed_publishers[1]
Order is not really stable? Maybe not the matter of this PR but might be worth opening an issue?

2016-12-12 11:31 UTC, pbougue commented on source/kraken/tests/realtime_test.cpp
> +    navitia::PbCreator pb_creator(data_ptr, boost::posix_time::from_iso_string("20150928T0830"), null_time_period);
is the dt really needed here? seems odd if it's the case.

2016-12-12 11:31 UTC, pbougue commented on source/kraken/worker.cpp
> +                              const pt::ptime now,
I'd name it `current_datetime`

2016-12-12 11:31 UTC, pbougue commented on source/kraken/worker.cpp
> +                                                *data,
indent

2016-12-12 11:31 UTC, pbougue commented on source/kraken/worker.cpp
> -                               disable_feedpublisher);
`disable_feedpublisher` not susceptible to be used downward?

2016-12-12 11:31 UTC, pbougue commented on source/kraken/worker.cpp
>                                               "Unable to parse : " + request.uri());
indent

2016-12-12 11:31 UTC, pbougue commented on source/kraken/worker.cpp
>                                                        boundary_duration, request_journey.max_transfers(),
indent

2016-12-12 11:31 UTC, pbougue commented on source/ptreferential/ptreferential_api.cpp
> +                             const type::Type_e requested_type,
indent

2016-12-12 11:31 UTC, pbougue commented on source/time_tables/request_handle.cpp
> +        } else if( !pb_creator.data->meta->production_date.contains((datetime + boost::posix_time::seconds(duration)).date()) ) {
line length

2016-12-12 11:31 UTC, pbougue commented on source/time_tables/request_handle.cpp
> +        if(! pb_creator.data->meta->production_date.contains(datetime.date()) ) {
) ) spacing

2016-12-12 12:40 UTC, TeXitoi commented on source/calendar/calendar_api.cpp
> -                              const boost::posix_time::ptime& current_datetime,
current_dt is in pb_convertor, and is used only in the function for pb_creator creation.

2016-12-12 12:43 UTC, TeXitoi commented on source/kraken/tests/realtime_test.cpp
> +    navitia::PbCreator pb_creator(data_ptr, boost::posix_time::from_iso_string("20150928T0830"), null_time_period);
I don't understand your remark.

2016-12-12 12:44 UTC, TeXitoi commented on source/kraken/worker.cpp
> +                              const pt::ptime now,
That's already the name of the member.

2016-12-12 12:45 UTC, TeXitoi commented on source/kraken/worker.cpp
> -                               disable_feedpublisher);
it's in the pb_creator.

2016-12-12 12:50 UTC, TeXitoi commented on source/jormungandr/tests/ptref_tests.py
> +        feed_publisher = feed_publishers[1]
```c++
std::set<const nt::Contributor*> contributors;
```
I'll open another PR to handle that.

2016-12-12 13:06 UTC, pbougue commented on source/kraken/tests/realtime_test.cpp
> +    navitia::PbCreator pb_creator(data_ptr, boost::posix_time::from_iso_string("20150928T0830"), null_time_period);
Weird to use both current and requested dt