add poi into map
hove-io/navitia pull request #1914
Opened 2017-01-03 10:59 UTC by xlqian

http://jira.canaltp.fr/browse/ITI-189

2017-01-03 11:01 UTC, xlqian commented
adding test...

2017-01-03 11:20 UTC, pbougue reviewed
Looks like it can be mutualized with the ongoing PR from @azime (not sure though): https://github.com/CanalTP/navitia/pull/1903/commits/28b92824c74675ba59e660233eacfc1cae5c0c9d

2017-01-03 12:46 UTC, xlqian commented
@pbougue 👍

2017-01-04 17:10 UTC, TeXitoi requested changes

2017-01-04 17:10 UTC, TeXitoi commented on source/jormungandr/jormungandr/scenarios/experimental.py
> +    return getattr(attr, "coord", None)
please mutualize this with...

2017-01-05 09:48 UTC, TeXitoi requested changes

2017-01-05 09:48 UTC, TeXitoi commented on source/jormungandr/jormungandr/street_network/tests/valhalla_test.py
> +def format_url_func_with_different_ptobject():
Without test in the name, I don't think it will be run.

2017-01-05 09:48 UTC, TeXitoi commented on source/jormungandr/jormungandr/utils.py
> +    >>> pt_object = response_pb2.Response()
useless line

2017-01-05 10:51 UTC, pbougue commented on source/jormungandr/jormungandr/street_network/tests/valhalla_test.py
> +def format_url_func_with_different_ptobject():
try to add an `assert False` in every test... :sob:

2017-01-05 11:03 UTC, pbougue approved these changes

2017-01-05 11:09 UTC, TeXitoi approved these changes

2017-01-05 11:35 UTC, merged