All: Line sections on ptref
hove-io/navitia pull request #1977
Opened 2017-02-14 13:16 UTC by antoine-de

this PR is part of the work on how to display the [line sections](https://github.com/CanalTP/navitia/blob/dev/documentation/rfc/line_sections.md)

For the moment we display the line section impact as before (as a line impact), on the impacted stop_points and impacted vehicle_journeys

2017-02-14 14:43 UTC, pbougue commented
Jenkins, test this please

2017-02-15 08:14 UTC, kinnou02 approved these changes

2017-02-15 16:01 UTC, TeXitoi requested changes
:+1:

2017-02-15 16:01 UTC, TeXitoi commented on source/ed/build_helper.cpp
> +    link_informed_entity(dis::make_pt_obj(type, uri, *b.data->pt_data), impact, b.data->meta->production_date, get_disruption().rt_level);
long line

2017-02-15 16:01 UTC, TeXitoi commented on source/jormungandr/tests/line_sections_tests.py
> +        assert not self.has_disruption(ObjGetter('vehicle_journeys', 'vj:1:2'), 'line_section_on_line_1')
No journey test?

2017-02-15 16:01 UTC, TeXitoi commented on source/type/message.cpp
> +
useless empty line

2017-02-15 16:01 UTC, TeXitoi commented on source/type/message.h
> +    friend void link_informed_entity(PtObj ptobj, boost::shared_ptr<Impact>& impact, const boost::gregorian::date_period&, type::RTLevel);
Maybe a static method is more appropriate than a friend function?

2017-02-15 16:06 UTC, antoine-de commented on source/jormungandr/tests/line_sections_tests.py
> +        assert not self.has_disruption(ObjGetter('vehicle_journeys', 'vj:1:2'), 'line_section_on_line_1')
nop they are for the next PR :wink:

2017-02-15 23:16 UTC, TeXitoi approved these changes

2017-02-16 10:38 UTC, merged