Jormungandr: rename experimental to distributed
hove-io/navitia pull request #2066
Opened 2017-04-24 13:40 UTC by xlqian

rename experimental to distributed

2017-04-26 13:31 UTC, pbougue approved these changes

2017-04-26 13:31 UTC, pbougue commented on source/jormungandr/jormungandr/instance.py
>                  logger.exception('sceneario not found')
`scenario` (no `e`)

2017-04-27 12:30 UTC, pbougue requested changes
Not done before, but it would be nice to add it to tyr: https://github.com/CanalTP/navitia/blob/dev/source/tyr/tyr/resources.py#L386

2017-04-28 16:59 UTC, pbougue approved these changes

2017-04-28 17:00 UTC, pbougue commented
Jenkins, test this please

2017-05-02 07:05 UTC, antoine-de commented
Jenkins, test this please

2017-05-02 08:28 UTC, merged