add p+r parking using STAR service
hove-io/navitia pull request #2177
Opened 2017-08-10 14:18 UTC by xlqian

https://jira.canaltp.fr/browse/NAVP-669

2017-08-10 15:05 UTC, kinnou02 requested changes

2017-08-10 15:05 UTC, kinnou02 commented on source/jormungandr/jormungandr/default_settings.py
> +CAR_PARKING_PROVIDER = []
It would be nice to enable configuration by envvar too

2017-08-10 15:05 UTC, kinnou02 commented on source/jormungandr/jormungandr/interfaces/v1/Journeys.py
> +        if parser_get.parse_args().get("bss_stands") or parser_get.parse_args().get("car_parking"):
we should add a more generic parameter if the two always work together

2017-08-10 15:05 UTC, kinnou02 commented on source/jormungandr/jormungandr/parking_space_availability/abstrcat_parking_places_provider.py
> +class AbstrcatParkingPlacesProvider(six.with_metaclass(ABCMeta, object)):
typo

2017-08-10 15:05 UTC, kinnou02 commented on source/jormungandr/jormungandr/parking_space_availability/car/parking_places.py
> +        self.available_disabled = available_disabled
disabled as a translation for "PMR"?

2017-08-10 15:05 UTC, kinnou02 commented on source/jormungandr/jormungandr/parking_space_availability/car/star.py
> +        self.breaker = pybreaker.CircuitBreaker(fail_max=5, reset_timeout=10)
it better if we can configure it, and 10 second of timeout is really low

2017-08-10 15:05 UTC, kinnou02 commented on source/jormungandr/jormungandr/parking_space_availability/car/star.py
> +    def __init__(self, operators, timeout, dataset, feed_publisher=DEFAULT_STAR_FEED_PUBLISHER):
you should put a default timeout, 2sec is a great value, or at least the one currently use

2017-08-10 15:05 UTC, kinnou02 commented on source/navitiacommon/navitiacommon/models.py
> +    car_parking_provider = db.Column(db.Boolean, default=default_values.car_parking_provider,
I didn't see any migration for this change

2017-08-10 15:05 UTC, kinnou02 commented on source/jormungandr/jormungandr/parking_space_availability/car/star.py
> +            logging.getLogger(__name__).error('STAR service dead (error: {})'.format(e))
You should take advantage of the new json logging mechanize.
You can look at timeo or siri_lite for some example

2017-08-10 15:05 UTC, kinnou02 commented on source/jormungandr/jormungandr/parking_space_availability/car/star.py
> +            logging.getLogger(__name__).error('STAR service dead (error: {})'.format(e))
Also it will be nice to add some metrology with newrelic, again you can find example in timeo

2017-08-11 07:24 UTC, xlqian commented on source/jormungandr/jormungandr/default_settings.py
> +CAR_PARKING_PROVIDER = []
Done

2017-08-11 07:28 UTC, xlqian commented on source/jormungandr/jormungandr/interfaces/v1/Journeys.py
> +        if parser_get.parse_args().get("bss_stands") or parser_get.parse_args().get("car_parking"):
`show_parking_availability`?

2017-08-11 07:30 UTC, xlqian commented on source/jormungandr/jormungandr/parking_space_availability/abstrcat_parking_places_provider.py
> +class AbstrcatParkingPlacesProvider(six.with_metaclass(ABCMeta, object)):
Done

2017-08-11 07:53 UTC, xlqian commented on source/jormungandr/jormungandr/parking_space_availability/car/parking_places.py
> +        self.available_disabled = available_disabled
hmmm "PRM"?

2017-08-11 07:53 UTC, xlqian commented on source/jormungandr/jormungandr/parking_space_availability/car/star.py
> +    def __init__(self, operators, timeout, dataset, feed_publisher=DEFAULT_STAR_FEED_PUBLISHER):
ok

2017-08-11 07:57 UTC, xlqian commented on source/jormungandr/jormungandr/interfaces/v1/Journeys.py
> +        if parser_get.parse_args().get("bss_stands") or parser_get.parse_args().get("car_parking"):
`show_parking_status`? `parking_status`?

2017-08-11 08:12 UTC, xlqian commented on source/jormungandr/jormungandr/parking_space_availability/car/star.py
> +        self.breaker = pybreaker.CircuitBreaker(fail_max=5, reset_timeout=10)
Oops, i forgot that one...

2017-08-11 08:23 UTC, xlqian commented on source/jormungandr/jormungandr/parking_space_availability/car/star.py
> +            logging.getLogger(__name__).error('STAR service dead (error: {})'.format(e))
ok

2017-08-11 09:15 UTC, xlqian commented on source/navitiacommon/navitiacommon/models.py
> +    car_parking_provider = db.Column(db.Boolean, default=default_values.car_parking_provider,
oops

2017-08-11 16:40 UTC, TeXitoi commented on source/jormungandr/jormungandr/parking_space_availability/car/car_parking_provider_manager.py
> +                item['parking_places'] = provider.get_informations(item)
What append if the provider is down?

2017-08-11 16:41 UTC, TeXitoi commented on source/jormungandr/jormungandr/parking_space_availability/car/parking_places.py
> +        self.occupied_PRM = occupied_PRM
PMR and not PRM, and it's french for "Personne à Mobilité Réduite", thus we need an english term.

2017-08-11 16:44 UTC, TeXitoi commented on source/jormungandr/jormungandr/parking_space_availability/car/star.py
> +        occupied_PRM = jmespath.search('records[0].fields.nombreplacesoccupeespmr', data) or 0
field not present and 0 must be different. If not present, that's maybe just that the API does not provide the information, not that there is no disabled slots.

2017-08-11 16:45 UTC, TeXitoi commented on source/navitiacommon/navitiacommon/models.py
> +    car_parking_provider = db.Column(db.Boolean, default=default_values.car_parking_provider,
done

2017-08-14 06:56 UTC, xlqian commented on source/jormungandr/jormungandr/parking_space_availability/car/parking_places.py
> +        self.occupied_PRM = occupied_PRM
PRM is the english term... person with reduced mobility

2017-08-17 09:56 UTC, TeXitoi commented on source/jormungandr/jormungandr/parking_space_availability/car/parking_places.py
> +        self.occupied_PRM = occupied_PRM
OK, my bad.

2017-08-17 14:41 UTC, xlqian commented on source/jormungandr/jormungandr/parking_space_availability/car/star.py
> +        occupied_PRM = jmespath.search('records[0].fields.nombreplacesoccupeespmr', data) or 0
done

2017-08-17 16:53 UTC, TeXitoi commented on source/jormungandr/jormungandr/interfaces/v1/Journeys.py
> +
Doc for doc.navitia.io!

2017-08-17 16:55 UTC, TeXitoi commented on source/jormungandr/jormungandr/interfaces/v1/Places.py
> +                                         "in the pois(bicycle_rental, car parking) of response")
doc!

2017-08-18 16:31 UTC, pbougue commented on documentation/slate/source/includes/apis.md
> +  nop      | parking_status  | boolean     | Activate the output of parking availability(BSS, car parking etc.) in the bicycle_rental, car parking pois of response     | True
Maybe a table of enum? (bss, car)
And also maybe deprecate `bss_stands`?

2017-08-18 16:31 UTC, pbougue commented on source/jormungandr/jormungandr/parking_space_availability/__init__.py
> +from abstrcat_parking_places_provider import AbstractParkingPlacesProvider
typo: `abstract_`

2017-08-18 16:31 UTC, pbougue commented on source/jormungandr/jormungandr/parking_space_availability/car/parking_places.py
> +        if available_PRM is not None and occupied_PRM is not None:
To be done attribute by attribute (then object is dismissed if all is None)

2017-08-18 16:31 UTC, pbougue commented on source/jormungandr/jormungandr/parking_space_availability/car/parking_places.py
> +        self.total_stands = available + occupied
sum of all partitions (it will be easier to understand if the rest, PRM included, is a partition)

2017-08-18 16:31 UTC, pbougue commented on source/jormungandr/jormungandr/parking_space_availability/abstract_provider_manager.py
> +def get_from_to_pois_of_journeys(journeys):
minor: looks like something needed elsewhere and we can mutualize

2017-08-18 16:31 UTC, pbougue commented on source/jormungandr/jormungandr/parking_space_availability/car/star.py
> +    WS_URL_TEMPLATE = 'http://data.explore.star.fr/api/records/1.0/search/?dataset={}&refine.idparc={}'
should be a param? (same for bss)

2017-08-21 07:59 UTC, xlqian commented on source/jormungandr/jormungandr/parking_space_availability/abstract_provider_manager.py
> +def get_from_to_pois_of_journeys(journeys):
hasn't this been done?

2017-08-21 08:01 UTC, xlqian commented on source/jormungandr/jormungandr/parking_space_availability/car/star.py
> +    WS_URL_TEMPLATE = 'http://data.explore.star.fr/api/records/1.0/search/?dataset={}&refine.idparc={}'
same thing should be done to jcdecaux

2017-08-21 09:41 UTC, pbougue commented on source/jormungandr/jormungandr/parking_space_availability/car/star.py
> +            self.record_call("OK")
needs to record "failure" also ;)

2017-08-21 10:18 UTC, xlqian commented on source/jormungandr/jormungandr/parking_space_availability/car/star.py
> +    WS_URL_TEMPLATE = 'http://data.explore.star.fr/api/records/1.0/search/?dataset={}&refine.idparc={}'
this will be done only for STAR in this PR, another PR will be opened for jcdecaux

2017-08-21 16:53 UTC, pbougue commented on documentation/slate/source/includes/apis.md
> +  nop      | add_poi_infos  | boolean      | Activate the output of additional infomations about the poi. For example, parking availability(BSS, car parking etc.) in the bicycle_rental, car parking p
"pass `add_poi_infos[]=&` (empty string) to deactivate all" would be clearer I think

2017-08-21 17:07 UTC, merged