New chaos channel types added in navitia
hove-io/navitia pull request #2233
Opened 2017-10-24 10:45 UTC by kadhikari

- New  channel types 'title' and 'beacon' added.
- Some tests added

2017-10-24 12:19 UTC, kinnou02 requested changes

2017-10-24 12:19 UTC, kinnou02 commented on source/kraken/make_disruption_from_chaos.cpp
>              throw navitia::exception("Unhandled ChannelType value in Chaos.Proto");
we should apply the same rules between disruptions from the database or directly from chaos.
So the default case should put an `Channel_Type_unkown_type`.
Also a log when this happen will be useful

2017-10-24 14:25 UTC, pbougue approved these changes

2017-10-24 14:25 UTC, pbougue commented on source/kraken/make_disruption_from_chaos.cpp
> +                            "Unhandled ChannelType value in Chaos.Proto: unknown_type used");
minor: indent (1 extra space) + I'd rather have unknown always just before default (but it's minor)

2017-10-24 16:13 UTC, TeXitoi approved these changes

2017-10-26 06:37 UTC, kinnou02 approved these changes

2017-10-26 08:19 UTC, merged