Doc: clearer basics
hove-io/navitia pull request #2358
Opened 2018-03-09 19:46 UTC by pbougue

"Approach" and "Who's who" sections should be duplicated in README ?

2018-03-12 17:52 UTC, stifoon requested changes

2018-03-12 17:52 UTC, stifoon commented on documentation/slate/source/includes/welcome.md
> +It's main purpose is to provide day-to-day informations to travelers.
"**Its**" main purpose

2018-03-12 17:52 UTC, stifoon commented on documentation/slate/source/includes/welcome.md
> +Over time Navitia has become doing way more, _sometimes_ for technical and debuging purpose _or_ because other functional needs fit quite well in what Navitia can do _or_ just because it was easy and
Over "**the**" time Navitia has "**became**"

2018-03-13 16:21 UTC, pbougue commented
I trust more @nonifier remarks on English...
Maybe @TeXitoi and @stifoon have an opinion if I should duplicate it on the README ?
Anyway, expect some delays for revisions on this PR, has the work here is disturbed by a big (BIG) amount of fresh :snowflake: all over the :mountain_snow: , both on slopes and off-pist, so :skier: and :tada: is compulsory :-/

2018-03-13 17:13 UTC, nonifier commented on documentation/slate/source/includes/examples.md
> +Here `/coverage/sandbox/stop_areas/stop_area:RAT:SA:BASTI/lines/line:RAT:M5/` means we are looking for informations on everything that is in the region _"sandbox"_ and that is stricly related to both
`informations` always is singular ;)

2018-03-13 17:13 UTC, nonifier commented on documentation/slate/source/includes/examples.md
> +4. **Parameters**, used to precise any additional detail linked to the endpoint requested.
`precise` is an adjective (even though it's a verb in French :p ). You could probably use `refine` here.

2018-03-19 11:22 UTC, stifoon approved these changes

2018-03-19 15:17 UTC, mbounabi approved these changes

2018-03-20 09:10 UTC, TeXitoi requested changes

2018-03-20 09:10 UTC, TeXitoi commented on documentation/slate/source/includes/examples.md
> +2. **Path**, used to filter the request and precise what is affected by the query. This filter is an instersection of multiple `key/value` (logical _AND_).
instersection?

2018-03-20 09:10 UTC, TeXitoi commented on documentation/slate/source/includes/examples.md
> +2. **Path**, used to filter the request and precise what is affected by the query. This filter is an instersection of multiple `key/value` (logical _AND_).
coverage is a bit special

2018-03-22 14:15 UTC, nonifier approved these changes

2018-03-26 16:05 UTC, TeXitoi approved these changes

2018-03-27 13:17 UTC, merged

2018-03-27 13:25 UTC, TeXitoi commented on readme.rst
> +Technically, Navitia is a [HATEOAS](http://en.wikipedia.org/wiki/HATEOAS) API that returns JSON formated results.
md link

2018-03-27 13:25 UTC, TeXitoi commented on readme.rst
> +Navitia is instanciated and exposed publicly through [api.navitia.io](http://api.navitia.io).
md link