tyr: create a new job to manage data injection towards mimir
hove-io/navitia pull request #2361
Opened 2018-03-13 15:17 UTC by kadhikari

- Ticket: https://jira.canaltp.fr/browse/NAVP-813

- For a data_set with family_type = 'pt' and an instance with  export to mimir activé, we create a new job and a data_set with family_type = 'mimir', and name = file path of source job (job with 'pt'). 
    
- In the function last_datasets the data_set with family_type = 'mimir' is excluded for backward compatibility of other apis. The function last_datasets is used many times.

- in the api "jobs" all the jobs and data-sets are listed with status of each job.

2018-03-15 10:00 UTC, kinnou02 requested changes

2018-03-15 10:00 UTC, kinnou02 commented on source/tyr/tyr/binarisation.py
> +                job.state = 'failed'
change will be rollbacked if you do not commit them.

2018-03-16 16:14 UTC, nonifier commented on source/tyr/tests/integration/dataset_test.py
> +def create_jobs_with_three_data_sets():
There is a lot of duplicated code from the test above. Could this be re-factored please ?

2018-03-16 16:14 UTC, nonifier commented on source/tyr/tests/integration/dataset_test.py
> +    assert len(resp) == 2
Same here regarding code duplication. Most of the asserts are already done above and should not be needed here.

2018-03-19 11:14 UTC, mbounabi commented on source/tyr/tests/integration/dataset_test.py
> +
What is the use of this test? There are already tests about last datasets.
Also, as mentionned by @nonifier , the next test does almost the same thing at the beginning

2018-03-19 11:14 UTC, mbounabi commented on source/tyr/tyr/tasks.py
> +    for action in actions:
At this point, the list 'actions' is empty, isn't it?

2018-03-23 10:47 UTC, kadhikari commented on source/tyr/tests/integration/dataset_test.py
> +
As already discussed with @mbounabi, here we test the result once with one job having two data_sets and then after adding a new job with a data_set with family_type 'mimir'. We should have the same result as data_set with family_type 'mimir' is filtered in this pull request.

2018-03-23 10:50 UTC, kadhikari commented
jenkins test this please

2018-03-23 15:32 UTC, mbounabi approved these changes

2018-03-23 16:00 UTC, nonifier approved these changes
Looking good :)

2018-03-26 18:01 UTC, pbougue approved these changes

2018-03-28 05:58 UTC, kinnou02 approved these changes

2018-03-30 17:04 UTC, merged