ed: correction for a pattern with dst.
hove-io/navitia pull request #2384
Opened 2018-04-04 15:07 UTC by kadhikari

For a pattern with period intersecting two dsts, if the pattern is
active only one day and shift <> 0 then do not shift.

Concerned ticket: https://jira.canaltp.fr/browse/NAVITIAII-2411

Some infomations in the tickets

2018-04-06 08:31 UTC, pbougue reviewed
As discussed, and to be explicit here: this needs testing.
> :heavy_check_mark: done

2018-04-06 08:31 UTC, pbougue commented on source/type/type.cpp
> +        if (!(vj.validity_patterns[0]->days.count() == 1) && (vj.shift != 0)) {
Please use enum `base_schedule` explicitly.

2018-04-06 08:31 UTC, pbougue commented on source/type/type.cpp
> +        if (!(vj.validity_patterns[0]->days.count() == 1) && (vj.shift != 0)) {
What has to be implemented (for this patch) is just: don't modify a vj that has a valid base_schedule vp.
You are testing too much things here.

2018-04-11 16:21 UTC, pbougue approved these changes

2018-04-12 09:55 UTC, nonifier requested changes

2018-04-12 09:55 UTC, nonifier commented on source/ed/docker_tests/ed_integration_tests.cpp
> +    BOOST_REQUIRE_EQUAL(data.pt_data->lines.size(), 1);
Why do you require `lines` and `routes` to have a size of 1 when you don't access them ? Maybe they are `BOOST_CHECK_*` instead ?

2018-04-12 09:55 UTC, nonifier commented on source/ed/docker_tests/ed_integration_tests.cpp
> +    BOOST_CHECK_EQUAL(data.pt_data->vehicle_journeys[0]->dataset->uri, "SCF:23");
You might need a `BOOST_REQUIRE_GT(data.pt_data->lines.size(), 1);` before this check. Otherwise, your test will crash if you have no VJ.

2018-04-12 10:34 UTC, nonifier approved these changes

2018-04-12 12:36 UTC, merged