Jormungandr: Close SOAP session
hove-io/navitia pull request #2418
Opened 2018-05-24 15:16 UTC by mbounabi

https://jira.kisio.org/browse/NAVITIAII-2377

2018-05-24 15:24 UTC, kinnou02 approved these changes

2018-05-24 15:24 UTC, kinnou02 commented on source/jormungandr/jormungandr/parking_space_availability/bss/atos.py
>      def _get_client(self):
You might want to delete the old implementation of `_get_client`

2018-05-24 15:24 UTC, kinnou02 commented on source/jormungandr/jormungandr/parking_space_availability/bss/atos.py
>      def _get_client(self):
there is no impact to recreate the `client` at each call?

2018-05-24 15:24 UTC, kinnou02 requested changes
miss click

2018-05-25 08:31 UTC, mbounabi commented on source/jormungandr/jormungandr/parking_space_availability/bss/atos.py
>      def _get_client(self):
see first comment : no impact on performance

2018-05-25 13:05 UTC, mbounabi commented
@kinnou02, 'miss click' can be dismissed?

2018-05-25 13:09 UTC, kinnou02 approved these changes

2018-05-25 14:59 UTC, xlqian approved these changes

2018-05-25 14:59 UTC, xlqian commented on source/jormungandr/jormungandr/parking_space_availability/bss/atos.py
> +    @contextmanager
:+1:

2018-05-28 07:54 UTC, merged