Jormun & Kraken:  Add fare zone info in stop point
hove-io/navitia pull request #2427
Opened 2018-06-04 10:14 UTC by mbounabi

https://jira.kisio.org/browse/NAVITIAII-2460
Navitia-proto needed:
https://github.com/CanalTP/navitia-proto/pull/113

2018-06-05 09:08 UTC, kadhikari commented
A test with fare_zone and another without fare_zone will assure reviewers

2018-06-05 10:25 UTC, xlqian commented on source/jormungandr/jormungandr/interfaces/v1/serializer/pt.py
> +    fare_zone = FareZoneSerializer(attr='fare_zone', display_none=False)
minor: attr='fare_zone' is not necessary

2018-06-05 13:15 UTC, nonifier approved these changes

2018-06-05 13:18 UTC, nonifier requested changes
You need to update navitia-proto submodule so that Jenkins can build your PR.

2018-06-05 14:13 UTC, mbounabi commented on source/jormungandr/jormungandr/interfaces/v1/serializer/pt.py
> +    fare_zone = FareZoneSerializer(attr='fare_zone', display_none=False)
Indeed, it is not. But, for clarity and easier-to-read code, I suggest to write anyway. It doesn't impact performance or anything else.

2018-06-05 15:48 UTC, pbougue commented on source/type/pb_converter.cpp
> +    auto* farezone = stop_point->mutable_fare_zone();
This should be added only if sp->fare_zone is not empty to avoid useless fields in pb (then in json)

2018-06-05 15:49 UTC, pbougue commented on source/jormungandr/tests/journey_common_tests.py
> +            assert 'name' in r['journeys'][0]['sections'][1]['from']['stop_point']['fare_zone']
If it's easily doable, would be nice to add a fare zone and test actual name (also test that no fare_zone is outputed if no data is available)

2018-06-07 09:14 UTC, nonifier commented
What's up with this PR ?

2018-06-07 09:15 UTC, nonifier reviewed
What's up with this PR ?

2018-06-07 09:20 UTC, mbounabi commented
@nonifier : Currently working on the comments by @pbougue

2018-06-08 12:17 UTC, nonifier approved these changes

2018-06-08 12:34 UTC, pbougue commented on source/type/pb_converter.cpp
> +		auto* farezone = stop_point->mutable_fare_zone();
indent (your editor is probably badly configured : we use only spaces, no tab)

2018-06-08 12:34 UTC, pbougue commented on source/ed/build_helper.h
> +    /// Create a stopPoint in the current stopArea
:+1: :gb:

2018-06-08 12:34 UTC, pbougue commented on source/jormungandr/tests/journey_common_tests.py
> +import  os
minor: spacing

2018-06-08 16:47 UTC, pbougue approved these changes

2018-06-08 16:47 UTC, merged