Kraken: Do not display any disruption if parameter disable_disruption used
hove-io/navitia pull request #2525
Opened 2018-09-06 10:49 UTC by kadhikari

Ticket: https://jira.kisio.org/browse/NAVP-853

2018-09-07 07:31 UTC, xlqian approved these changes

2018-09-07 07:31 UTC, xlqian commented on source/jormungandr/tests/ptref_tests.py
> +        utc_datetime = '20140115T235959'
(you can add "Z" at the end of datetime to make it UTC )

2018-09-10 05:32 UTC, kinnou02 requested changes

2018-09-10 05:32 UTC, kinnou02 commented on source/type/pb_converter.cpp
> +    if (!pb_creator.disable_disruption) {
It's better to shortcircuit at the start of the function.
In line 1018 we add the uri of the impact to the object, with this change we do not put the disruption be still have the link to it.

2018-09-11 13:49 UTC, kinnou02 approved these changes

2018-09-12 08:38 UTC, merged