Add dateutil dependency to navitiacommon, and link it from tyr
hove-io/navitia pull request #2546
Opened 2018-09-26 10:41 UTC by nonifier

Proposal for splitting dependency requirements. 
As Tyr pulls navitiacommon, I want Tyr to relies on navitiacommon's dependencies; hence the new `requirements.txt` in navitiacommon.

This is a first step, but I would love to see all navitiacommon's requirements in the right files from now on :)

2018-09-26 11:54 UTC, pbougue reviewed
That's a nice idea ! Totally makes sense.
We should pass over all dependencies that are common to tyr, eitri and jormun to check if they should be in that navitiacommon's requirement.
Also, shouldn't you attach navitiacommon's requirement to eitri and jormun's requirements? (that's why I don't approve it now, but I'm not sure)

2018-09-26 13:39 UTC, nonifier commented
Thanks PE, I agree, there are way more dependencies that need to be reflected, but this PR mainly aims at fixing https://ci.navitia.io/job/deploy_navitia_on_dev/1216/.

I wanted this change to be minimal to be quickly reviewed and merged ;) But, yes, more work to be done in the future :construction_worker_man:

2018-09-26 13:41 UTC, benoit-bst approved these changes

2018-09-26 13:41 UTC, kinnou02 requested changes
This requirements file are packaged and deployed on the production server, as such reference to others file won't work and prevent deployment

2018-09-26 13:47 UTC, benoit-bst commented
So, maybe it's time to update deployment scripts or it's too expensive?

2018-09-26 13:50 UTC, nonifier commented
@kinnou02 : How does deployment work then? Do we not install the dependencies via pip in production?

2018-09-26 15:01 UTC, nonifier commented
Ok, I've removed the requirement file... because deployment = pile of mud ^^

2018-09-26 15:24 UTC, benoit-bst commented
![yoda](https://user-images.githubusercontent.com/32099204/46090355-d9f64380-c1b0-11e8-8097-807efcb080d2.jpeg)
Fighting you can not always win...

2018-09-26 15:24 UTC, benoit-bst approved these changes

2018-09-27 06:02 UTC, kinnou02 approved these changes

2018-09-27 06:02 UTC, merged