Jormun: Distributed refacto before breaking the whole thingy
hove-io/navitia pull request #2555
Opened 2018-10-03 10:14 UTC by nonifier

I've just prepared the codebase for the upcoming changes where journeys will be attached a crowfly before being filtered, only then, fallback will be computed.

The only change in the business logic is the fact that we are now waiting on the pt_journeys in the `call_kraken` *before* computing the fallback.

There is a new function in the scenario (`Scenario.finalise_journeys()`) that will be moved after the filtering.

2018-10-03 12:58 UTC, nonifier commented
Jenkins, retest this please

2018-10-03 15:38 UTC, nonifier commented
Jenkins, test this please

2018-10-04 08:15 UTC, xlqian reviewed
:+1:

2018-10-04 08:15 UTC, xlqian commented on source/jormungandr/jormungandr/scenarios/distributed.py
> +                self._scenario = Distributed(future_manager, request, instance, krakens_call)
`return Distributed(future_manager, request, instance, krakens_call)._compute_all()` and remove `self._scenario`?

2018-10-04 08:15 UTC, xlqian commented on source/jormungandr/jormungandr/scenarios/distributed.py
> +        future_manager = self.future_manager
I foresee a lot of conflicts....... be prepared :D

2018-10-09 05:22 UTC, kinnou02 requested changes

2018-10-09 05:22 UTC, kinnou02 commented on source/jormungandr/jormungandr/scenarios/distributed.py
> +        self._scenario = None
This class is used in a multithreaded context, so you should never use self to store thing.

2018-10-09 09:29 UTC, nonifier commented on source/jormungandr/jormungandr/scenarios/distributed.py
> +        self._scenario = None
:ok_hand:  I've now using the shared context class created by @kadhikari in his last PR.

2018-10-10 09:28 UTC, closed without merging