tyr: current jobs(state='running') with data_sets should not be deleted
hove-io/navitia pull request #2563
Opened 2018-10-09 15:04 UTC by kadhikari

Please see: https://jira.kisio.org/browse/NAVP-973 for details

2018-10-10 14:48 UTC, mbounabi approved these changes

2018-10-11 05:56 UTC, kinnou02 reviewed
The purge run everyday use the `last_datasets()` method: https://github.com/CanalTP/navitia/blob/dev/source/tyr/tyr/tasks.py#L344

2018-10-12 13:25 UTC, kinnou02 requested changes
Since this method isn't used it won't solve the problem

2018-10-16 18:00 UTC, pbougue approved these changes

2018-10-16 18:00 UTC, pbougue commented on source/navitiacommon/navitiacommon/models/__init__.py
> +            .order_by(Job.created_at.desc())
Why do you need that order?
If it's only for logging we can probably save it, or order it ascending as the more interesting (problematic) are the oldest ones.

2018-10-16 18:00 UTC, pbougue commented on source/tyr/tests/integration/purge_test.py
> +    deletinng jobs and theirs files on running state.
typo: deleting (one `n`) jobs and their (no `s`) `while` running.

2018-10-16 18:00 UTC, pbougue commented on source/tyr/tyr/tasks.py
> +    logger.info('running  data are: %s', running)
running `bina` are

2018-10-18 05:17 UTC, kinnou02 approved these changes

2018-10-19 07:01 UTC, merged