jormungandr: Add somes unit and integration test for disruption with a stop_time
hove-io/navitia pull request #2586
Opened 2018-11-06 15:40 UTC by kadhikari

2018-11-08 10:33 UTC, nonifier requested changes

2018-11-08 10:33 UTC, nonifier commented on source/jormungandr/tests/check_utils.py
> +    return len([d['id'] for d in response['disruptions'] if d['id'] == disrupt_id]) != 0
Using `any` would simplify the code/reading.

```suggestion
    return any([d['id'] for d in response['disruptions'] if d['id'] == disrupt_id])
```

2018-11-08 10:33 UTC, nonifier commented on source/kraken/tests/realtime_test.cpp
> +    b.data->build_raptor();
You have a convenient function to update the builder:  
```diff
-    b.data->build_uri();
-    pt_data->sort_and_index();
-    b.finish();
-    b.data->build_raptor();
+    b.make()
```

2018-11-08 15:02 UTC, nonifier approved these changes

2018-11-09 14:27 UTC, mbounabi approved these changes

2018-11-15 11:40 UTC, merged