Kraken: prioritize main stop_area over the others stop_area
hove-io/navitia pull request #2588
Opened 2018-11-12 16:37 UTC by kinnou02

With the change we reintroduce one of the rules used by navitia 1.
It allow data adminnistrators to increase the weight of some stop_area
by setting them as main stop_area.
This is a hack to make JLP happy: we need to found a better way to
implement this as main stop_area are used for admin to admin journeys
and geocoding.
You may want to set a coach station as the departure/arrival of a city
when doing long distance journeys, but it's a "minor" stop in the urban
network and even in the national network so you don't want to increase it's visibility when doing geocoding.

Test to come hopefuly!

2018-11-13 09:36 UTC, pbougue reviewed
So the "original" list of matches doesn't change, but its order does if I undestand correctly...
Can't we loose exact matches because of that ?
I'm thinking of an exact match that's not a main SA, in the middle of a long match list of main SA... Just getting the first 10 could remove that exact match, no ?

2018-11-13 09:36 UTC, pbougue commented on source/autocomplete/autocomplete_api.cpp
> +static std::set<std::string> get_main_stop_area(const navitia::type::Data& d){
naming: get_main_stop_area`s`

2018-11-13 16:03 UTC, benoit-bst commented
@pbougue, we need a test to respond of that. I think @kinnou02 is on the way :running_man:

2018-11-13 16:07 UTC, kinnou02 commented
@pbougue fair point, I can alter the scoring to keep exact match first

2018-11-14 11:28 UTC, nonifier commented on source/autocomplete/autocomplete_api.cpp
> +    std::set<std::string> result;
As long as you are only doing lookups into `result`, a `std::unordered_set` would be more suitable.

2018-11-14 11:28 UTC, nonifier commented on source/autocomplete/autocomplete_api.cpp
> +            bool a_is_main_sa = main_stop_areas.find(a.stop_area().uri()) != main_stop_areas.end();
minor: to simplify readability
```suggestion
            auto a_is_main_sa = main_stop_areas.count(a.stop_area().uri());
```

2018-11-20 14:13 UTC, benoit-bst approved these changes

2018-11-20 17:15 UTC, pbougue approved these changes
Don't you want to put a param in tyr instance's conf?

2018-11-21 06:23 UTC, kinnou02 commented
I would prefer not to have to do it if possible

2018-11-21 08:27 UTC, kadhikari approved these changes

2018-11-21 08:36 UTC, TeXitoi commented on source/autocomplete/autocomplete_api.cpp
> +            bool a_is_main_sa = main_stop_areas.find(a.stop_area().uri()) != main_stop_areas.end();
That's slower. I prefer the find personally.

2018-11-21 08:46 UTC, TeXitoi requested changes
Does the exact match problem fixed?

2018-11-21 08:46 UTC, TeXitoi commented on source/autocomplete/autocomplete_api.cpp
> +                        std::get<0>(r.scores) = std::get<0>(r.scores) * main_stop_area_weight_factor;
Minor

```suggestion
                        std::get<0>(r.scores) *= main_stop_area_weight_factor;
```

2018-11-21 08:46 UTC, TeXitoi commented on source/autocomplete/autocomplete_api.cpp
> +
```suggestion
```

2018-11-21 08:47 UTC, TeXitoi commented on source/autocomplete/autocomplete_api.cpp
> +            bool a_is_main_sa = main_stop_areas.find(a.stop_area().uri()) != main_stop_areas.end();
That's a set, so not slower, forget my comment, count is better.

2018-11-21 09:21 UTC, nonifier approved these changes

2018-11-21 10:03 UTC, TeXitoi approved these changes

2018-11-21 11:13 UTC, merged