Fix realtime test (on ubuntu 16.04)
hove-io/navitia pull request #2670
Opened 2019-02-05 15:07 UTC by benoit-bst

Currently, _realtime tests_ failed on **Ubuntu 16.04** but not on **Debian 8** and **Ubuntu 18**.
In fact, it is the `impact list order`, because it depends on protobuf version.

Impact list is coded with  :
`google::protobuf::RepeatedPtrField< ::pbnavitia::Impact >`

The test was develop on _ubuntu 18_. This is the reason why we didn't see it on ubuntu 16.04...

:heavy_check_mark:  I fixed and tested on **Ubuntu 16.04** and **debian 8**.

2019-02-05 16:20 UTC, kadhikari approved these changes

2019-02-06 08:46 UTC, TeXitoi commented
Why is there a difference on the order of the impacts?

2019-02-06 09:01 UTC, kinnou02 approved these changes

2019-02-06 09:24 UTC, benoit-bst commented
@TeXitoi, I don't known why, but the fact is that it happen. 
I suppose there is a difference into `google::protobuf::RepeatedPtrField` in the protobuf lib.
Anyway, before it was not safe in the test. We have to use an `id` to access a specific element.

2019-02-06 10:03 UTC, TeXitoi requested changes
I'd like that we understand why. There is maybe just somewhere we sort on a pointer value, maybe something worst.

2019-02-06 10:04 UTC, TeXitoi commented
`google::protobuf::RepeatedPtrField` is a vector, the difference is somewhere else.

2019-02-06 11:00 UTC, benoit-bst commented
to sum up : 

- `google::protobuf::RepeatedPtrField` is a vector, so the order is defined and unchanged
- There is a tuned`Less` comparator on Impact.
  ```

2019-02-06 14:39 UTC, benoit-bst commented
Aftermath invesgation, it results than in the code (pb_converter.h:176), the `std:set<...>Impact` needs a tuned `Less Comparator` (It was a lack). 
Now, for every OS, we have the good order : 
```
feed-1
feed-2
feed-3
```

End of the research :fireworks:

2019-02-06 15:22 UTC, TeXitoi approved these changes

2019-02-06 15:26 UTC, benoit-bst commented
Jenkins, test this please !

2019-02-06 16:14 UTC, merged