Document 'distance' field from 'Place' object in the swagger
hove-io/navitia pull request #2671
Opened 2019-02-06 17:34 UTC by nonifier

The SDK's team has reported a missing field in the swagger... Let's make them happy :)
```
"Place" : {
         "properties" : {
+          "distance" : {
+             "type" : "integer",
+             "description" : "Distance to the object in meters"
            },
            [...]
         },
         "type" : "object",
         "required" : [
            "name",
            "id"
         ]
      },
```

poke: @Guitouille  :)

2019-02-07 06:26 UTC, kinnou02 requested changes

2019-02-07 06:26 UTC, kinnou02 commented on source/jormungandr/jormungandr/interfaces/v1/serializer/pt.py
> +    embedded_type = EnumField(attr='embedded_type', required=False, pb_type=NavitiaType, display_none=True)
Seems strange to not have an `embedded_type` in places? when does it happen?

2019-02-07 06:26 UTC, kinnou02 commented on source/jormungandr/jormungandr/interfaces/v1/serializer/pt.py
> +    distance = jsonschema.IntField(required=False, display_none=True, description='Distance to the object in meters')
In `PlaceNearby` it was a str (yes that's ugly...). Remember that we can't change the interface, so if it was an `str` before it must stay one.
In `/place_nearby` it's an str:
```
{
    "distance": "104",
    "embedded_type": "poi",
    "id": "poi:osm:node:3889022681"
    "name": "Parking vélo (Paris)",
    "poi": ⊕{8 items},
    "quality": 0,
}
```

In `/places` it's an int...
```
{
    "address": ⊕{6 items},
    "distance": 4651,
    "embedded_type": "address",
    "id": "2.37715;48.846781"
    "name": "20 Rue Hector Malot (Paris)",
    "quality": 0,
}
```

2019-02-12 06:09 UTC, kinnou02 approved these changes

2019-02-12 14:29 UTC, kinnou02 approved these changes

2019-02-12 16:24 UTC, pbougue approved these changes
It's probably (too) complex: Can you add swagger tests on both bragi and kraken cases?
Maybe around here: https://github.com/CanalTP/navitia/blob/dev/source/jormungandr/tests/schema_tests.py#L215
This would help ensure both change at the same time.

2019-02-12 16:24 UTC, pbougue commented on source/jormungandr/tests/bragi_autocomplete_tests.py
>              assert r[0]['address']['label'] == '20 Rue Bob (Bobtown)'
maybe add a test on `id` as you overload it?

2019-02-13 10:08 UTC, merged