kraken: delete a queue after a timeout for a reload from kirin
hove-io/navitia pull request #2692
Opened 2019-02-27 13:10 UTC by kadhikari

https://jira.kisio.org/browse/NAVP-969

2019-02-27 13:15 UTC, kinnou02 requested changes

2019-02-27 13:15 UTC, kinnou02 commented on source/kraken/maintenance_worker.cpp
> +        channel->DeleteQueue(queue_name);
You should do it every time, even when we got a response.

2019-02-28 06:18 UTC, kinnou02 approved these changes

2019-02-28 13:12 UTC, pbougue approved these changes
This PR is fine.
As for the JIRA ticket itself, how about other queues created by Kraken? Are there some that should be deleted also?
This can be a new ticket, but it would be nice to also check that.

2019-02-28 13:12 UTC, pbougue commented on source/kraken/maintenance_worker.cpp
> +    // Finally we delete de queue as we create a new queque in each call to the function
typo: "delete `th`e queue [...] new queue (no extra `q`)"

2019-02-28 14:29 UTC, kadhikari commented on source/kraken/maintenance_worker.cpp
> +    // Finally we delete de queue as we create a new queque in each call to the function
Done

2019-03-01 12:18 UTC, merged