Properly linking fallback to pt in distributed
hove-io/navitia pull request #2714
Opened 2019-03-18 18:10 UTC by AurelienLP

https://jira.kisio.org/browse/NAVP-1243

2019-03-19 15:34 UTC, TeXitoi requested changes

2019-03-19 15:34 UTC, TeXitoi commented on source/jormungandr/jormungandr/scenarios/helper_classes/helper_utils.py
> +        fallback_sections[0].destination.CopyFrom(journey.sections[0].origin)
Need `fallback_sections[-1]` as a direct path can be several sections (parking, BSS...). Testing this could be great.

2019-03-19 15:38 UTC, xlqian approved these changes

2019-03-22 09:24 UTC, nonifier commented on source/jormungandr/jormungandr/scenarios/helper_classes/helper_utils.py
> +    def is_after_pt_sections(self):
Fair enough :)

2019-03-22 09:26 UTC, nonifier approved these changes

2019-03-25 08:15 UTC, TeXitoi approved these changes

2019-03-25 08:16 UTC, merged