Adding additional time for taxi
hove-io/navitia pull request #2715
Opened 2019-03-19 14:18 UTC by AurelienLP

https://jira.kisio.org/browse/NAVP-1235

2019-03-19 15:27 UTC, kadhikari requested changes

2019-03-19 15:27 UTC, kadhikari commented on source/tyr/tests/integration/instance_test.py
> +        "additional_time_before_last_section_taxi": 789,
You need to test these attributs as in https://github.com/CanalTP/navitia/blob/a6295cc80546d4f4560ffb6df513ba846172f254/source/tyr/tests/integration/instance_test.py#L351

2019-03-19 15:27 UTC, kadhikari commented on source/tyr/migrations/versions/52d628e535db_add_additional_time_for_taxi.py
> +    ### commands auto generated by Alembic - please adjust! ###
Better delete all auto generated comments

2019-03-19 15:27 UTC, kadhikari commented on source/navitiacommon/navitiacommon/default_values.py
> +# Additionnal time after the taxi section when used as first section mode
I guess time unit is second

2019-03-19 15:32 UTC, xlqian approved these changes

2019-03-20 08:41 UTC, kadhikari approved these changes

2019-03-20 10:39 UTC, merged