[Jormun] Use ridesharing connector in distributed
hove-io/navitia pull request #2743
Opened 2019-04-09 08:49 UTC by xlqian

This PR add a new connector Ridesharing in distributed.

The goal is to be able to manage ridesharing more properly.

Another goal is not to call Kraken twice when we have both taxi and ridesharing for the same fallback.

Sadly, only direct path is avoided to be called twice, the matrix is still called twice...

2019-04-25 13:30 UTC, kinnou02 approved these changes

2019-04-26 13:05 UTC, AurelienLP commented on source/jormungandr/jormungandr/street_network/taxi.py
> -                # Only for fallback
Could you please put this comment back ? :D

2019-04-26 13:07 UTC, AurelienLP requested changes
You just need to put the comment back in taxi, otherwise this is all good for me !

2019-04-29 09:09 UTC, AurelienLP approved these changes

2019-04-29 10:14 UTC, xlqian commented
Jenkins, test this please!

2019-04-29 14:20 UTC, merged