[Jormun] Adding street_network_configuraton in db
hove-io/navitia pull request #2839
Opened 2019-06-24 14:55 UTC by AurelienLP

https://jira.kisio.org/browse/TRR-52

2019-06-25 08:15 UTC, kinnou02 requested changes

2019-06-25 08:15 UTC, kinnou02 commented on source/tyr/migrations/versions/57f52a929056_street_network_configuration_db.py
> +        'instance', sa.Column('street_network_car', sa.Text(), nullable=False, server_default='kraken')
You have to add a foreignkey to the `street_network_configuration `

2019-06-25 08:15 UTC, kinnou02 commented on source/tyr/migrations/versions/57f52a929056_street_network_configuration_db.py
> +        'street_network_configuration',
I would prefer `streetnetwork_configuration` or even better for consistency `streetnetwork_backend`

2019-06-25 12:20 UTC, AurelienLP commented on source/tyr/migrations/versions/57f52a929056_street_network_configuration_db.py
> +        'street_network_configuration',
I'll go with streetnetwork_backend

2019-06-25 12:46 UTC, AurelienLP commented on source/tyr/migrations/versions/57f52a929056_street_network_configuration_db.py
> +        'instance', sa.Column('street_network_car', sa.Text(), nullable=False, server_default='kraken')
Don't we want `street_network_configuration` to be independent like the bss_provider table?

2019-06-25 14:26 UTC, kinnou02 commented on source/tyr/migrations/versions/57f52a929056_street_network_configuration_db.py
> +        'instance', sa.Column('street_network_car', sa.Text(), nullable=False, server_default='kraken')
bss providers aren't referenced by any coverage, they live freely.
here we want to have that association

2019-07-01 14:22 UTC, mbounabi commented on source/navitiacommon/navitiacommon/models/streetnetwork_backend.py
> +        self.klass = json['class']
```suggestion
        self.klass = json['klass']
```

This will cause some problems if a task streetnetwork_backend_diff is to be created in tyr-configurator.

2019-07-09 05:25 UTC, kinnou02 approved these changes

2019-07-09 07:49 UTC, kadhikari approved these changes

2019-07-09 09:55 UTC, mbounabi approved these changes

2019-07-09 09:57 UTC, merged