kraken: Stop times is over computed with frequencies.txt
hove-io/navitia pull request #2856
Opened 2019-07-10 07:15 UTC by benoit-bst

Currently, we have the following behavior

- **fusio2ed** fills `ed::data` struct with stop_times (_stop_times.txt_ file)

stop_times.txt example
![stop_times](https://user-images.githubusercontent.com/32099204/60899702-2fe13700-a26b-11e9-9552-94855be6b223.png)

- If **frequencies.txt** exists with the same `trip_id`, **fusio2ed** shifts all the stop times to the frequencies starting value (_start_time_ col)

frequencies.txt example
![frequencies](https://user-images.githubusercontent.com/32099204/60899870-7fbffe00-a26b-11e9-806a-515caca5efc0.png)

- But a bug is introduced because of an untimely function (_finalize_frequency_ function). 
In fact, after the _fusioParser_ calling, **fusio2ed** calls `data.complete()` which calls `finalize_frequency()`. 
This is an over computing that create wrong stop times values around zero.

- Solution, don't call `finalize_frequency()` and tests it with an Utest :unicorn: 

This PR shows that we need some extra _RFC doc_ about this mechanism. Maybe in a future PR.

2019-07-10 07:20 UTC, benoit-bst commented on source/ed/tests/fusioparser_test.cpp
> +    BOOST_CHECK_EQUAL(vj->stop_time_list[0]->departure_time, "05:00:00"_t);
Without the fix the result are
vj->stop_time_list[0]->departure_time = 5
vj->stop_time_list[1]->departure_time = 15
vj->stop_time_list[2]->departure_time = 25
vj->stop_time_list[3]->departure_time = 35

2019-07-11 07:30 UTC, kinnou02 commented
I don't think this is a valid change, still investigating how trip planning with freqVJ works

2019-07-11 07:58 UTC, kinnou02 requested changes
you broke [`get_next_stop_time`](https://github.com/CanalTP/navitia/blob/dev/source/routing/next_stop_time.cpp#L531)

also tests mostly do the same thing: https://github.com/CanalTP/navitia/blob/dev/source/ed/build_helper.cpp#L735-L754

2019-07-15 10:32 UTC, benoit-bst commented
Hoo, I don't see tests inside `next_stop_time_test` broken.
Maybe it is a little bit hidden ?

Currently, the process is as follows :

- The parser calls  [`FrequenciesGtfsHandler::handle_line`](https://github.com/CanalTP/navitia/blob/dev/source/ed/connectors/gtfs_parser.cpp#L1085)
we compute like https://github.com/CanalTP/navitia/blob/dev/source/ed/build_helper.cpp#L735-L754

- [`finalize_frequency`](https://github.com/CanalTP/navitia/blob/dev/source/ed/data.cpp#L741) function is called
It seems to be used only in [`ed::Data::complete()`](https://github.com/CanalTP/navitia/blob/dev/source/ed/data.cpp#L278) and in [`tests`](https://github.com/CanalTP/navitia/blob/dev/source/ed/tests/fusioparser_test.cpp#L259) (My **Rg** said that). 
I don't see why `get_next_stop_time` is impacted. Can you help me @kinnou02 ?

2019-07-16 09:31 UTC, benoit-bst commented
So, the final act of this PR is a close, because the fix can't work without a side effect...
A new PR will be open to add information inside `/vehicle_journeys` API response just to higlight that it is a **Frequency Vehicle Journey** (add `start_time end_time headway_secs` values)

2019-07-16 09:31 UTC, closed without merging