Unify and fix all python libraries version among all python projets
hove-io/navitia pull request #2876
Opened 2019-07-18 08:12 UTC by GuillaumeLescure

2019-07-18 10:05 UTC, kinnou02 requested changes

2019-07-18 10:05 UTC, kinnou02 commented on source/jormungandr/requirements.txt
> +protobuf==3.9.0
no, we want to keep the version available on the system, that why we do not fix the version.

2019-07-18 12:24 UTC, GuillaumeLescure commented on source/jormungandr/requirements.txt
> +protobuf==3.9.0
Ok, done

2019-07-18 14:09 UTC, GuillaumeLescure commented
Test this please.

2019-07-22 14:13 UTC, GuillaumeLescure commented
Jenkins, test this please

2019-07-22 14:26 UTC, mbounabi commented
I don't undertand what keeps you from doing the whole navitia env before this PR? Why upgrading some packages only?

2019-07-23 08:23 UTC, mbounabi approved these changes

2019-07-24 09:05 UTC, AurelienLP approved these changes

2019-07-25 14:34 UTC, GuillaumeLescure commented
Jenkins, test this please

2019-07-25 14:36 UTC, GuillaumeLescure commented
Jenkins, test this please.

2019-07-25 15:27 UTC, merged