[Tests] Chaos disruption tests
hove-io/navitia pull request #2923
Opened 2019-08-07 13:48 UTC by nonifier

## TL;DR
Long time awaited tests that cover Chaos disruptions database access ! 

## How does this works:
The new test is part of `docker_test` suite (eg. `make docker_test`), as it  shares the same dependencies. 

You can also run the test separately with `make chaos_tests`  

The test is a pytest that will pop a Postgres database in a Docker. The db's content comes from the sql file `source/tests/chaos/chaos_loading.sql`. Once the database is ready, a subprocess is triggered to call on `chaos_db_tests` a boost's test suite that will read the disruptions from the database and expect on the output `chaos::Disruption` protobuf objects.

2019-08-08 08:01 UTC, kinnou02 commented on source/kraken/fill_disruption_from_database.h
> +using Chaos_disruption_applier = std::function<
You have to choose between CamelCase and snake_case, since it's a type I would say CamelCase

2019-08-08 08:01 UTC, kinnou02 commented on source/tests/chaos/CMakeLists.txt
> +include_directories("..")
?

2019-08-08 08:01 UTC, kinnou02 commented on source/tests/chaos/Pipfile
> +url = "https://pypi.org/simple"
should we mix `Pipfile` and `requirements.txt` inside one repository?

2019-08-08 14:59 UTC, nonifier commented on source/tests/chaos/Pipfile
> +url = "https://pypi.org/simple"
It's_now_Been-removed.

2019-08-08 15:47 UTC, kinnou02 approved these changes

2019-08-12 14:03 UTC, pbougue requested changes
:+1: After a quick test locally, it should work fine, and it should be possible to know quickly what test is broken.
So those tests are automatable :tada: Great job! 

In addition to comments:

* After the pipenv removal, it misses a requirements_dev.txt for these tests (probably getting what's usefull from tyr/requirements_dev.txt, as it worked with it locally).
* It also misses a readme to explain how to update/create sql file.
* And maybe a readme update to explain how to launch it: better to launch directly it in travis if possible ?

2019-08-12 14:03 UTC, pbougue commented on source/tests/chaos/CMakeLists.txt
> +    COMMAND CHAOS_DB_TESTS_BUILD_DIR=${CHAOS_DB_TESTS_BUILD_DIR} py.test ${CHAOS_TESTS_PATH}
PostgresDocker import is failing:
It misses `PYTHONPATH=${CMAKE_CURRENT_SOURCE_DIR}:${CMAKE_SOURCE_DIR}/navitiacommon` here

2019-08-12 14:03 UTC, pbougue commented on source/tests/chaos/chaos_db_tests.cpp
> +    BOOST_CHECK_EQUAL(disruption.reference(), "msa-20190620172619");
Is it possible to explain what's tested here?
Maybe also a PR comment to link to the PR that was correcting this.

Did you try those tests without the fix?

2019-08-12 14:30 UTC, xlqian commented on source/tests/chaos/chaos_db_tests.cpp
> +    auto disruption_callback = [&disruptions](const chaos::Disruption& d, navitia::type::PT_Data&,
:+1:

2019-08-12 14:35 UTC, xlqian approved these changes

2019-08-12 17:11 UTC, nonifier commented on source/tests/chaos/CMakeLists.txt
> +    COMMAND CHAOS_DB_TESTS_BUILD_DIR=${CHAOS_DB_TESTS_BUILD_DIR} py.test ${CHAOS_TESTS_PATH}
well spotted ! I've had a `PYTHONPATH` with `navitiacommon` exported on my dev env...

2019-08-12 17:18 UTC, nonifier commented on source/tests/chaos/chaos_db_tests.cpp
> +    BOOST_CHECK_EQUAL(disruption.reference(), "msa-20190620172619");
Nope I didn't try this without the fix as it was done quite some time ago and I would have diverged significantly unfortunately. 

Also, I wanted here to test the order of the disruptions that was affected by the fix. You can see that with `BOOST_CHECK_EQUAL(disruptions[0/1/2/3/4].id(), "idxxxx"`

I also wanted to make sure we have assertions on the output protobuf, and ensure objects are constructed well with no sub-objects missing. That what you have in the second part of the test when we check all the fields from `disruptions[0]`.

2019-08-12 17:28 UTC, nonifier commented
@pbougue :

> After the pipenv removal, it misses a requirements_dev.txt for these tests (probably getting what's usefull from tyr/requirements_dev.txt, as it worked with it locally).

I've added a readme explaining that we have the same dependencies as the `docker_test`, and how to run those tests separately.  

---

> It also misses a readme to explain how to update/create sql file.

There is no easy way to create/update the sql file as it comes from a dump of a real database. We couldn't think of something easier to maintain this with intelligible values unfortunately.   

---

> And maybe a readme update to explain how to launch it: better to launch directly it in travis if possible ?

I've added a `readme.md` with some explanation. I can complete it if you think I've missed something that might be of interest. 
Regarding Travis, I tried to get it under CI, but building `chaos_db_tests` would required most of the cpp dependencies (log4cpp, boost etc...) and quite frankly, I just couldn't be bothered :(

2019-08-12 18:53 UTC, pbougue approved these changes
One big step for the tests! :footprints: 
:ok_hand: Nice work, and one can later comment or plug it to travis if needed

- [x] Please just change the tyr requirements`_dev` to use.

As for the maintenance, OK then I guess one would have to load the SQL dump, then migrate it if it requires some (using https://github.com/CanalTP/Chaos/tree/master/migrations), then handcraft it to add some rows :white_check_mark:

2019-08-12 18:53 UTC, pbougue commented on source/tests/chaos/readme.md
> +pip install -r ../../tyr/requirements.txt -r ../../eitri/requirements.txt
You have to use tyr/requirements`_dev`.txt for pytest (and after a local test, eitri/requirements.txt isn't needed for chaos_tests).

So you can pick any of the 2 for the doc:
For a specific chaos_tests venv
```suggestion
pip install -r ../../tyr/requirements_dev.txt
```
Or for a whole docker_test venv
```suggestion
pip install -r ../../tyr/requirements_dev.txt -r ../../eitri/requirements.txt
```

2019-08-13 10:03 UTC, nonifier commented
jenkins, please test this.

2019-08-14 08:21 UTC, nonifier commented
Jenkins, test this please

2019-08-14 09:12 UTC, merged