jormungandr: Limiting param count value to 200 except for journeys
hove-io/navitia pull request #3324
Opened 2020-11-18 08:24 UTC by kadhikari

Ticket: https://jira.kisio.org/browse/NAVITIAII-3240

2020-11-18 08:34 UTC, SGrenet requested changes
max_count has to be at 200 for /places only
other endpoints don't have to change now

(except journeys in my opinion for which max_count 1000 is too much, but is an other subject because isochron can be impacted)

2020-11-19 09:50 UTC, SGrenet approved these changes

2020-11-20 16:18 UTC, xlqian approved these changes

2020-11-23 15:16 UTC, azime approved these changes

2020-11-25 13:11 UTC, nonifier approved these changes

2020-12-03 16:12 UTC, merged