[TYR] handle multiple files and job ids
hove-io/navitia pull request #3534
Opened 2021-08-31 11:20 UTC by xlqian

2021-09-03 09:06 UTC, kadhikari requested changes

2021-09-03 09:06 UTC, kadhikari commented on source/tyr/tyr/binarisation.py
> +            job_ids = get_named_arg('job_ids', func, args, kwargs) or []
Where do we add argument_name 'job_ids' in kwargs ?

2021-09-03 09:06 UTC, kadhikari commented on source/tyr/tyr/binarisation.py
> +            job = models.Job.query.get(job_ids[0])
We always get the first job but about other jobs ?

2021-09-03 09:06 UTC, kadhikari commented on source/tyr/tyr/binarisation.py
> +    logger = get_instance_logger(instance, jobs_ids=[job_id])
Only one job id for jobs_ids ?

2021-09-03 09:06 UTC, kadhikari commented on source/tyr/tyr/binarisation.py
> +            job.state = 'failed'
If one job fail, it will penalize all the other jobs ?

2021-09-03 09:06 UTC, kadhikari commented on source/tyr/tyr/tasks.py
> +            new_job.state = 'running'
Here we loose all the new_job created from second to second last  file without job id.

2021-09-06 08:30 UTC, xlqian commented on source/tyr/tyr/binarisation.py
> +            job_ids = get_named_arg('job_ids', func, args, kwargs) or []
it's a decorator, 'jod_ids' come from the wrapped function..

2021-09-06 08:32 UTC, xlqian commented on source/tyr/tyr/binarisation.py
> +            job = models.Job.query.get(job_ids[0])
yes, in fact, the reason why we extract a job from the db is to get the instance, and all jobs SHOULD possess the same instance,

2021-09-06 08:32 UTC, xlqian commented on source/tyr/tyr/binarisation.py
> +    logger = get_instance_logger(instance, jobs_ids=[job_id])
yes

2021-09-06 08:32 UTC, xlqian commented on source/tyr/tyr/binarisation.py
> +            job.state = 'failed'
yep

2021-09-06 12:37 UTC, kadhikari approved these changes

2021-09-07 12:50 UTC, pbench approved these changes

2021-09-07 12:50 UTC, pbench commented on source/tyr/tests/integration/datapost_test.py
> +    assert not os.path.isfile('/tmp/_JOB_ID_DELIMITER_1_JOB_ID_DELIMITER_fusio.zip')
Maybe 
```suggestion
    assert not os.path.isfile('/tmp/<JOB_ID_DELIMITER>1<JOB_ID_DELIMITER>fusio.zip')
```
as below ?

2021-09-07 12:50 UTC, pbench commented on source/tyr/tyr/__init__.py
> +JOB_ID_DELIMITER = "<JOB_ID_DELIMITER>"
This will be written as part of filenames right ? 
It seems strange to me to use "<>" in filenames. Why not  "_JOB_ID_DELIMITER_" ?

2021-09-07 12:50 UTC, pbench commented on source/tyr/tyr/binarisation.py
> +    assert jobs
Maybe log an error message and raise an exception instead of crashing ?

2021-09-07 12:50 UTC, pbench commented on source/tyr/tyr/binarisation.py
> +    assert jobs
Maybe log an error message and raise an exception instead of crashing ?

2021-09-07 13:57 UTC, merged